import React from'react';import{AbsoluteFill,Audio,Easing,interpolate,OffthreadVideo,Sequence,staticFile,useCurrentFrame}from'remotion';
const N='#071d2d',G='#078b76',M='#42d3b1',R='#bd2437',C='#f4f1e8';
const cues=[
[4,32,'QUER SABER UM'],[32,71,'ERRO QUE PODE CUSTAR'],[71,105,'MUITO DINHEIRO'],[105,148,'PARA UMA PEQUENA EMPRESA'],[1038,1098,'SE VOCÊ É EMPRESÁRIO'],[1098,1125,'E TEM FUNCIONÁRIOS'],[1132,1183,'ESSE É UM ASSUNTO RELEVANTE'],[1183,1202,'PARA VOCÊ']
]as const;
const anim=(f:number,s:number,e:number)=>Math.min(interpolate(f,[s,s+7],[0,1],{extrapolateLeft:'clamp',extrapolateRight:'clamp',easing:Easing.out(Easing.cubic)}),interpolate(f,[e-6,e],[1,0],{extrapolateLeft:'clamp',extrapolateRight:'clamp'}));
const Tag=()=> <div style={{position:'absolute',top:590,right:55,background:R,color:'white',padding:'18px 30px',font:'900 38px Arial',letterSpacing:1}}>PARAUAPEBAS</div>;
const Caption:React.FC<{s:number;e:number;t:string}>=({s,e,t})=>{const f=useCurrentFrame(),p=anim(f,s,e);return <div style={{position:'absolute',top:1780,left:70,right:70,textAlign:'center',font:'900 62px Arial',lineHeight:1.08,color:'white',textShadow:'0 5px 13px #000',opacity:p,filter:`blur(${(1-p)*8}px)`,transform:`translateY(${(1-p)*20}px)`}}>{t}</div>};
const Hook=()=>{const f=useCurrentFrame();return <><Tag/><div style={{position:'absolute',left:60,right:60,top:1460,textAlign:'center',font:'900 72px Arial',lineHeight:1.02,color:'white',textShadow:'0 5px 16px #000'}}>{f>=35&&f<80&&<span style={{color:R}}>UM ERRO</span>}{f>=80&&<div style={{color:M,fontSize:96}}>CUSTA CARO</div>}</div></>};
const Full:React.FC<{children:React.ReactNode;bg?:string}>=({children,bg=N})=><AbsoluteFill style={{background:bg,color:'white',fontFamily:'Arial',alignItems:'center',justifyContent:'center',textAlign:'center'}}>{children}</AbsoluteFill>;
const Planning=()=>{const f=useCurrentFrame()-161,p=anim(f,0,115);return <Full><div style={{font:'900 50px Arial',color:'#b6cbd3',letterSpacing:4}}>O ERRO ESTÁ NA</div><div style={{font:'900 92px Arial',color:M,transform:`translateY(${(1-p)*40}px)`,filter:`blur(${(1-p)*10}px)`}}>FALTA DE<br/>PLANEJAMENTO</div><div style={{marginTop:60,font:'900 44px Arial',border:`4px solid ${M}`,padding:'24px 50px'}}>ANTES DA CONTRATAÇÃO</div></Full>};
const Compare=()=>{const f=useCurrentFrame()-276;const beyond=interpolate(f,[216,235],[0,1],{extrapolateLeft:'clamp',extrapolateRight:'clamp'});return <Full bg={C}><div style={{color:G,font:'900 48px Arial',letterSpacing:3}}>O CUSTO NÃO É APENAS</div><div style={{display:'flex',gap:35,marginTop:75}}>{['LÍQUIDO DA FOLHA','IMPOSTOS'].map((x,i)=><div key={x} style={{width:500,padding:'45px 20px',background:'white',color:N,font:'900 50px Arial',boxShadow:'0 15px 35px #09202a22',transform:`translateY(${interpolate(f,[30+i*55,48+i*55],[35,0],{extrapolateLeft:'clamp',extrapolateRight:'clamp'})}px)`}}>{x}</div>)}</div><div style={{marginTop:90,color:R,font:'900 78px Arial',opacity:beyond,transform:`scale(${.85+beyond*.15})`}}>VAI MUITO ALÉM</div></Full>};
const Costs=()=>{const f=useCurrentFrame()-547;const its=[['ADMISSÃO',31],['BENEFÍCIOS',70],['FÉRIAS',118],['OBRIGAÇÕES',162],['DESLIGAMENTO',242]]as const;return <Full bg={`linear-gradient(145deg,${C},#dce9e5)`}><div style={{position:'absolute',top:410,color:G,font:'900 54px Arial'}}>O CUSTO REAL ENVOLVE</div><div style={{display:'flex',flexDirection:'column',gap:30}}>{its.map(([x,s],i)=>{const p=interpolate(f,[s,s+14],[0,1],{extrapolateLeft:'clamp',extrapolateRight:'clamp',easing:Easing.out(Easing.back(1.1))});return <div key={x} style={{width:950,color:N,font:'900 61px Arial',padding:'28px',background:'white',borderLeft:`12px solid ${i===4?R:G}`,opacity:p,transform:`translateX(${(1-p)*(i%2?-100:100)}px)`,boxShadow:'0 12px 28px #071d2d22'}}>{String(i+1).padStart(2,'0')} · {x}</div>})}</div></Full>};
const Health=()=>{const f=useCurrentFrame()-811,p=interpolate(f,[150,175],[0,1],{extrapolateLeft:'clamp',extrapolateRight:'clamp'});return <Full><div style={{font:'900 48px Arial',color:'#aac5cf'}}>CONSIDERE TODOS OS CUSTOS</div><div style={{margin:'70px 0',font:'900 82px Arial',color:M}}>TODO MÊS</div><div style={{width:850,height:24,background:'#294553',borderRadius:20,overflow:'hidden'}}><div style={{height:'100%',width:`${p*100}%`,background:M}}/></div><div style={{marginTop:45,font:'900 66px Arial'}}>SAÚDE FINANCEIRA<br/><span style={{color:M}}>DA SUA EMPRESA</span></div></Full>};
const CTA=()=>{const f=useCurrentFrame()-1213,p=interpolate(f,[12,28],[0,1],{extrapolateLeft:'clamp',extrapolateRight:'clamp'}),press=interpolate(f,[190,198,207],[1,1.1,1],{extrapolateLeft:'clamp',extrapolateRight:'clamp'});return <Full><div style={{font:'900 54px Arial',color:M}}>SAIBA O CUSTO REAL</div><div style={{marginTop:25,font:'900 86px Arial'}}>DA SUA FOLHA<br/>DE PAGAMENTO</div><div style={{marginTop:90,background:R,borderRadius:70,padding:'30px 90px',font:'900 58px Arial',opacity:p,transform:`scale(${press})`,boxShadow:'0 0 45px #bd243777'}}>SOLICITE UMA ANÁLISE</div></Full>};
export const Integra03:React.FC=()=>{const f=useCurrentFrame();const full=f>=161&&f<1038||f>=1213;return <AbsoluteFill style={{background:'#000'}}><OffthreadVideo src={staticFile('integra03.mp4')} style={{width:'100%',height:'100%',objectFit:'cover'}}/>{!full&&f<161&&<Hook/>}{!full&&f>=1038&&<><Tag/>{cues.filter(([s,e])=>f>=s&&f<e).map(([s,e,t])=><Caption key={s}s={s}e={e}t={t}/>)}</>}{f>=161&&f<276&&<Planning/>}{f>=276&&f<547&&<Compare/>}{f>=547&&f<811&&<Costs/>}{f>=811&&f<1038&&<Health/>}{f>=1213&&<CTA/>}{[161,276,547,811,1213].map((x,i)=><Sequence key={x} from={x} durationInFrames={38}><Audio src={staticFile(`sfx/${i%2?'transition-tech.mp3':'transition-soft.mp3'}`)} volume={.34}/></Sequence>)}{[578,617,665,709,789].map(x=><Sequence key={x} from={x} durationInFrames={22}><Audio src={staticFile('sfx/hitech-touch-magnet.mp3')} volume={.24}/></Sequence>)}<Sequence from={1403} durationInFrames={20}><Audio src={staticFile('sfx/ui-select-click.mp3')} volume={.46}/></Sequence></AbsoluteFill>};
