import React from 'react';
import {AbsoluteFill,Audio,Easing,Img,OffthreadVideo,Sequence,interpolate,interpolateColors,staticFile,useCurrentFrame} from 'remotion';
import {Caption} from './Caption';
import {cues} from './captions';

const RED='#9d1730', RED2='#c92442', CREAM='#fff7eb', INK='#271017';
const CityTag=()=> <div style={{position:'absolute',top:575,right:52,background:RED,color:'#fff',padding:'15px 23px 14px',font:'800 34px Arial',letterSpacing:.5,boxShadow:'0 5px 14px rgba(0,0,0,.28)'}}>PARAUAPEBAS E REGIÃO</div>;

const OpeningHook=()=>{const frame=useCurrentFrame();const enter=interpolate(frame,[7,27],[0,1],{extrapolateLeft:'clamp',extrapolateRight:'clamp',easing:Easing.out(Easing.cubic)});const exit=interpolate(frame,[56,67],[0,1],{extrapolateLeft:'clamp',extrapolateRight:'clamp',easing:Easing.in(Easing.cubic)});const visible=enter*(1-exit);const words=['ESSA','OPORTUNIDADE','É PARA','VOCÊ'];return <div style={{position:'absolute',inset:0,overflow:'hidden',fontFamily:'Arial,Helvetica,sans-serif',pointerEvents:'none'}}><div style={{position:'absolute',left:0,right:0,top:1370,height:900,background:'linear-gradient(180deg,transparent,rgba(25,8,12,.58) 35%,rgba(25,8,12,.18) 82%,transparent)'}}/><div style={{position:'absolute',left:70,right:70,top:1510,textAlign:'center',lineHeight:.98,textShadow:'0 5px 13px rgba(0,0,0,.72)'}}>{words.map((w,i)=>{const p=interpolate(frame,[10+i*4,30+i*4],[0,1],{extrapolateLeft:'clamp',extrapolateRight:'clamp',easing:Easing.out(Easing.cubic)});return <div key={w} style={{fontSize:i===3?112:67,fontWeight:900,letterSpacing:i===3?2:5,color:i===3?'#ff375b':'#fff',opacity:p*(1-exit),filter:`blur(${(1-p)*10+exit*9}px)`,transform:`translateY(${(1-p)*40-exit*16}px)`}}>{w}</div>})}</div><Img src={staticFile('hand-pointing-transparent.png')} style={{position:'absolute',width:640,height:640,objectFit:'contain',left:400,bottom:-45,opacity:visible,filter:`blur(${(1-enter)*11+exit*10}px) drop-shadow(0 14px 18px rgba(0,0,0,.34))`,transform:`translateY(${(1-enter)*105+exit*60}px) scale(${.91+enter*.09})`}}/></div>};

const Areas=()=>{const frame=useCurrentFrame();const local=frame-1043;const bg=interpolate(local,[0,10,101,112],[0,1,1,0],{extrapolateLeft:'clamp',extrapolateRight:'clamp'});return <AbsoluteFill style={{background:`linear-gradient(145deg,${CREAM},#f4d9d8)`,opacity:bg,justifyContent:'center',alignItems:'center',fontFamily:'Arial',color:INK}}><div style={{position:'absolute',width:900,height:900,borderRadius:'50%',background:'rgba(201,36,66,.08)',transform:`scale(${1+local*.0008})`}}/><div style={{transform:`translateY(${interpolate(local,[0,112],[18,-18])}px)`,textAlign:'center'}}><div style={{fontSize:44,fontWeight:800,letterSpacing:10,color:RED2}}>SÃO</div><div style={{fontSize:210,fontWeight:900,lineHeight:.9,color:RED}}>3 ÁREAS</div><div style={{marginTop:72,display:'flex',flexDirection:'column',gap:28}}>{['TESTA','GLABELA','PÉS DE GALINHA'].map((s,i)=>{const start=24+i*15;const p=interpolate(local,[start,start+28],[0,1],{extrapolateLeft:'clamp',extrapolateRight:'clamp',easing:Easing.out(Easing.back(1.15))});return <div key={s} style={{fontSize:76,fontWeight:900,letterSpacing:3,opacity:Math.min(1,p*2.2),transform:`scale(${.78+p*.22}) translateY(${14*(1-p)}px)`}}>{s}</div>})}</div></div></AbsoluteFill>};

const targets=[8,9,9,0]; const ROW=230;
const posAt=(f:number,i:number)=>{const d=targets[i],s=14+i*7,p0=.85*s,T=Math.ceil((p0+6-d)/10)*10+d;if(f<s)return .85*Math.max(f,0);if(f<s+16)return interpolate(f,[s,s+16],[p0,T+.5],{easing:Easing.out(Easing.cubic),extrapolateLeft:'clamp',extrapolateRight:'clamp'});if(f<s+22)return interpolate(f,[s+16,s+22],[T+.5,T],{easing:Easing.out(Easing.cubic),extrapolateLeft:'clamp',extrapolateRight:'clamp'});return T};
const Reel=({frame,i}:{frame:number;i:number})=>{const pos=posAt(frame,i);return <div style={{width:142,height:ROW,overflow:'hidden',position:'relative'}}><div style={{position:'absolute',transform:`translateY(${-(pos%10)*ROW}px)`}}>{Array.from({length:20},(_,k)=><div key={k} style={{width:142,height:ROW,lineHeight:`${ROW}px`,textAlign:'center',fontSize:205,fontWeight:900,fontVariantNumeric:'tabular-nums'}}>{k%10}</div>)}</div></div>};
const Price=()=>{const frame=useCurrentFrame(),local=frame-1155;const lock=63,pulse=interpolate(local,[lock,lock+4,lock+8],[1,1.04,1],{extrapolateLeft:'clamp',extrapolateRight:'clamp'}),ink=interpolateColors(local,[lock,lock+4,lock+8],[INK,'#000',INK]),sub=interpolate(local,[63,83],[0,1],{extrapolateLeft:'clamp',extrapolateRight:'clamp',easing:Easing.out(Easing.cubic)});return <AbsoluteFill style={{background:`linear-gradient(150deg,#f7d8d9,${CREAM})`,justifyContent:'center',alignItems:'center',fontFamily:'Arial',color:ink}}><div style={{fontSize:38,fontWeight:900,letterSpacing:8,color:RED2,marginBottom:42}}>CONDIÇÃO ESPECIAL</div><div style={{display:'flex',alignItems:'center',transform:`scale(${pulse})`}}><div style={{fontSize:116,fontWeight:900,marginRight:22}}>R$</div><Reel frame={local} i={0}/><Reel frame={local} i={1}/><div style={{fontSize:190,fontWeight:900}}>,</div><Reel frame={local} i={2}/><Reel frame={local} i={3}/></div><div style={{marginTop:50,fontSize:64,fontWeight:900,letterSpacing:5,color:RED,opacity:sub,filter:`blur(${(1-sub)*12}px)`,transform:`translateY(${(1-sub)*25}px)`}}>12 PARCELINHAS</div></AbsoluteFill>};

export const MaraizaBotox01:React.FC=()=>{const frame=useCurrentFrame();const special=frame>=1043&&frame<1258;const hook=frame>=7&&frame<67;return <AbsoluteFill style={{background:'#000'}}><OffthreadVideo src={staticFile('maraiza-botox01.mp4')}/>{!special&&<><CityTag/><div style={{position:'absolute',left:90,right:90,top:1750,height:205,display:'flex',alignItems:'center',justifyContent:'center'}}>{!hook&&cues.filter(c=>frame>=c.start&&frame<c.end).map(c=><Caption key={c.start} cue={c}/>)}</div></>}{hook&&<OpeningHook/>}{frame>=1043&&frame<1155&&<><AbsoluteFill style={{background:`linear-gradient(145deg,${CREAM},#f4d9d8)`}}/><Areas/></>}{frame>=1155&&frame<1258&&<Price/>}
<Sequence from={7} durationInFrames={32}><Audio src={staticFile('sfx/transition-soft.mp3')} volume={.28}/></Sequence>
<Sequence from={1043} durationInFrames={35}><Audio src={staticFile('sfx/transition-soft.mp3')} volume={.35}/></Sequence>
{[1085,1130].map((x,i)=><Sequence key={x} from={x} durationInFrames={20}><Audio src={staticFile('sfx/pop-electric.mp3')} volume={.22+i*.02}/></Sequence>)}
<Sequence from={1155} durationInFrames={90}><Audio src={staticFile('sfx/data-compute.mp3')} volume={.25}/></Sequence>
{[1191,1198,1205,1212].map(x=><Sequence key={x} from={x} durationInFrames={15}><Audio src={staticFile('sfx/lock-quick.mp3')} volume={.16}/></Sequence>)}
<Sequence from={1218} durationInFrames={25}><Audio src={staticFile('sfx/bass-hit-short.mp3')} volume={.22}/></Sequence>
</AbsoluteFill>};
