const {test}=require('node:test'),assert=require('node:assert/strict'),{Readable}=require('node:stream'),crypto=require('node:crypto');
const {createCampaignManager}=require('../Dashboard Meta Ads/campaign-manager');
function fixture(options={}){
 const store=new Map(),calls=[],nodes=new Map();let sequence=100,revision='one';
 const user={id:'a'},conn={token:'private-test-token',revision:'one',scopes:options.readOnly?['ads_read']:['ads_read','ads_management']};
 const graph=async(token,object)=>{if(object==='act_111/ads')return {data:options.sourceAds||[]};if(object==='search')return {data:[{key:'city1',type:'city',name:'Belém',country_code:'BR',region:'Pará'}]};if(object==='777')return {status:{video_status:options.videoError?'error':options.processing?'processing':'ready'}};return nodes.get(object)||{id:object,account_id:object==='999'?'222':'111',campaign_id:'10',destination_type:options.existingDestination||'WEBSITE',promoted_object:{page_id:'1'},status:'PAUSED',effective_status:'PAUSED'}};
 const rows=async(token,edge)=>edge.endsWith('/promote_pages')?[{id:'1',name:'Page'}]:edge.endsWith('/instagram_accounts')?[{id:'2',username:'ig'}]:edge.endsWith('/leadgen_forms')?[{id:'3',status:'ACTIVE'}]:edge.endsWith('/thumbnails')?[{uri:'https://example.test/thumb.jpg'}]:[...nodes.values()].filter(x=>edge.endsWith('/'+x.edge));
 const api=createCampaignManager({graph,rows,planCampaign:options.planner|| (async()=>({name:"AI draft",headline:"Title",message:"Copy",dailyBudget:30,category:"",rationale:"Suggestion",destination:"site",locationQuery:"Bel?m",ageMin:18,ageMax:65,interestQueries:[],placements:"automatic"})),authorizeAccounts:async(u,ids)=>{if(ids[0]!=='act_111')throw Object.assign(new Error('Account denied'),{status:403});return {conn,accounts:[{id:'act_111',currency:'BRL'}]}},connection:()=>({...conn,revision}),read:(k,u)=>store.get(k+':'+u),write:(k,u,v)=>store.set(k+':'+u,v),fetchImpl:async(url,opts)=>{const endpoint=url.pathname.split('/').slice(2).join('/'),params=opts.body instanceof URLSearchParams?Object.fromEntries(opts.body):opts.body;calls.push({endpoint,params});assert.equal(opts.headers.Authorization,'Bearer private-test-token');if(options.failure&&endpoint.endsWith(options.failure))return {ok:false,json:async()=>({error:{error_user_msg:'Invalid targeting'}})};let payload;if(endpoint.endsWith('/adimages'))payload={images:{file:{hash:'image-hash'}}};else if(endpoint.endsWith('/advideos'))payload={id:'777'};else if(!endpoint.includes('/')){const item=nodes.get(endpoint);if(item){item.status=params.status;item.effective_status=params.status}payload={success:true}}else{const id=String(++sequence);nodes.set(id,{id,account_id:'111',name:params.name,status:params.status,effective_status:params.status,edge:endpoint.split('/')[1]});payload={id}}if(options.changeConnection)revision='two';return {ok:true,json:async()=>payload}}});
 const run=(action,p,who=user,account='act_111')=>api.handle(Object.assign(Readable.from(p?[Buffer.from(JSON.stringify(p))]:[]),{method:p?'POST':'GET'}),who,new URL('https://test/api/ads-manager/'+action.replace('&','?')+(action.includes('&')?'&':'?')+'account='+account));
 const draft=(extra={})=>({key:crypto.randomUUID(),confirm:true,name:'Campaign',headline:'Headline',message:'Ad text',destination:'site',url:'https://example.test',page:'1',media:'image',dailyBudget:'35.50',countries:['BR'],ageMin:18,ageMax:65,...extra});
 store.set('ads-media:a',[{key:'image',account:'act_111',kind:'image',value:'image-hash'},{key:'video',account:'act_111',kind:'video',value:'777'}]);
 return {run,draft,calls,store,nodes};
}
test('new site campaign creates all levels paused, exact minor-unit budget and no token returned',async()=>{const f=fixture(),p=f.draft(),result=await f.run('create',p);assert.equal(result.state,'complete');assert.equal(f.calls.length,4);for(const c of f.calls.filter(x=>!x.endpoint.endsWith('adcreatives')))assert.equal(c.params.status,'PAUSED');assert.equal(f.calls[1].params.daily_budget,'3550');assert.equal(f.calls[0].params.objective,'OUTCOME_TRAFFIC');assert.ok(!JSON.stringify(result).includes('private-test-token'));assert.deepEqual(await f.run('create',p),result);assert.equal(f.calls.length,4)});
test('WhatsApp and lead forms use their own objectives, destinations and CTAs',async()=>{for(const destination of ['whatsapp','form']){const f=fixture();await f.run('create',f.draft({destination,phone:'5594999999999',form:'3',instagram:'2'}));assert.equal(f.calls[0].params.objective,destination==='form'?'OUTCOME_LEADS':'OUTCOME_ENGAGEMENT');assert.equal(f.calls[1].params.destination_type,destination==='form'?'ON_AD':'WHATSAPP');const story=JSON.parse(f.calls[2].params.object_story_spec);assert.equal(story.instagram_user_id,'2');assert.equal(story.link_data.call_to_action.type,destination==='form'?'SIGN_UP':'WHATSAPP_MESSAGE')}});
test('existing compatible adset creates only the creative and paused ad',async()=>{const f=fixture();await f.run('create',f.draft({adset:'11'}));assert.equal(f.calls.length,2);assert.equal(f.calls[1].params.adset_id,'11');assert.equal(f.calls[1].params.status,'PAUSED')});
test('rejects wrong account, missing write permission, foreign page, Instagram and media',async()=>{const f=fixture();await assert.rejects(f.run('create',f.draft(),{id:'a'},'act_222'),/denied/);await assert.rejects(f.run('create',f.draft({page:'9'})),/Página/);await assert.rejects(f.run('create',f.draft({instagram:'9'})),/Instagram/);await assert.rejects(f.run('create',f.draft(),{id:'b'}),/criativo/);const readOnly=fixture({readOnly:true});await assert.rejects(readOnly.run('create',readOnly.draft()),/gerenciamento/);assert.equal(f.calls.length,0);assert.equal(readOnly.calls.length,0)});
test('rejects foreign or incompatible adsets and inactive/foreign lead forms before mutation',async()=>{const f=fixture();for(const p of [f.draft({adset:'999'}),f.draft({adset:'11',destination:'whatsapp',phone:'5594999999999'}),f.draft({destination:'form',form:'9'})])await assert.rejects(f.run('create',p));assert.equal(f.calls.length,0)});
test('partial failure records created IDs and blocks retry of the same operation',async()=>{const f=fixture({failure:'adsets'}),p=f.draft();await assert.rejects(f.run('create',p),/Invalid targeting/);const result=await f.run('operations');assert.equal(result.items[0].state,'needs_review');assert.equal(result.items[0].created.campaign,'101');await assert.rejects(f.run('create',p),/registrada/);assert.equal(f.calls.length,2)});
test('video waits for readiness; ready video uses the thumbnail and video creative',async()=>{const pending=fixture({processing:true});await assert.rejects(pending.run('create',pending.draft({media:'video'})),/processado/);assert.equal(pending.calls.length,0);const f=fixture();await f.run('create',f.draft({media:'video'}));assert.equal(JSON.parse(f.calls[2].params.object_story_spec).video_data.video_id,'777')});
test('explicit status confirmation and exact typed account edge are required',async()=>{const f=fixture();const r=await f.run('create',f.draft());await assert.rejects(f.run('status',{kind:'ad',id:r.created.campaign,status:'ACTIVE',confirm:true}),/autorizado/);await assert.rejects(f.run('status',{kind:'ad',id:r.created.ad,status:'ACTIVE'}),/Confirme/);const result=await f.run('status',{kind:'ad',id:r.created.ad,status:'ACTIVE',confirm:true});assert.equal(result.item.status,'ACTIVE')});
test('upload checks actual file signature and scopes, then registers media per user/account',async()=>{const f=fixture();await assert.rejects(f.run('upload',{type:'image/png',data:Buffer.from('not a png').toString('base64')}),/conteúdo/);const result=await f.run('upload',{type:'image/png',data:Buffer.from('89504e470d0a1a0a','hex').toString('base64')});assert.equal(result.kind,'image');assert.equal(f.store.get('ads-media:a').at(-1).account,'act_111');assert.equal(f.store.get('ads-media:b'),undefined)});
test('connection change stops further writes and leaves an operation requiring review',async()=>{const f=fixture({changeConnection:true});await assert.rejects(f.run('create',f.draft()),/conexão mudou/);assert.equal(f.calls.length,1);assert.equal((await f.run('operations')).items[0].state,'needs_review')});
test('invalid budget and URL cannot create any objects; special categories use broad age range',async()=>{const f=fixture();await assert.rejects(f.run('create',f.draft({dailyBudget:-1})));await assert.rejects(f.run('create',f.draft({url:'javascript:alert(1)'})));assert.equal(f.calls.length,0);await f.run('create',f.draft({category:'HOUSING',ageMin:25,ageMax:40}));const t=JSON.parse(f.calls[1].params.targeting);assert.equal(t.age_min,18);assert.equal(t.age_max,65)});

test('quick planning uses authorized assets and verified geography without creating ads',async()=>{const f=fixture();const locations=await f.run('locations&q=Be');const location=locations.items[0];const result=await f.run('plan',{description:'Quero uma campanha de consultoria em Bel?m para receber contatos pelo WhatsApp.'});assert.equal(result.reviewRequired,true);assert.equal(result.draft.location.name,'Belém');assert.equal(f.calls.length,0);await f.run('create',f.draft({location:result.draft.location}));assert.deepEqual(JSON.parse(f.calls[1].params.targeting).geo_locations,{cities:[{key:'city1'}]});});


test('JPEG and MP4 uploads use the correct Meta transport and preserve media ownership',async()=>{for(const [type,data,kind] of [['image/jpeg','ffd8ffe000104a464946','image'],['video/mp4','00000018667479706d703432000000006d70343269736f6d','video']]){const f=fixture();const result=await f.run('upload',{type,data:Buffer.from(data,'hex').toString('base64')});assert.equal(result.kind,kind);const call=f.calls[0];assert.equal(call.endpoint,kind==='image'?'act_111/adimages':'act_111/advideos');if(kind==='video'){const file=call.params.get('source');assert.equal(file.type,'video/mp4');assert.equal(file.name,'creative.mp4');assert.deepEqual(Buffer.from(await file.arrayBuffer()),Buffer.from(data,'hex'));}assert.equal(f.store.get('ads-media:a').at(-1).account,'act_111');}});
test('oversized and mismatched files cannot reach Meta; failed video does not create campaigns',async()=>{const f=fixture();await assert.rejects(f.run('upload',{type:'image/jpeg',data:Buffer.alloc(20*1024*1024+1,255).toString('base64')}),/20 MB/);await assert.rejects(f.run('upload',{type:'video/mp4',data:Buffer.from('this is not an mp4').toString('base64')}),/formato/);assert.equal(f.calls.length,0);const failed=fixture({videoError:true});await assert.rejects(failed.run('create',failed.draft({media:'video'})),/outro MP4/);assert.equal(failed.calls.length,0);});

test('intelligent planning requires a meaningful description and does not create ads',async()=>{const f=fixture();await assert.rejects(f.run('plan',{description:'short'}),/12 a 1500/);assert.equal(f.calls.length,0)});
test('intelligent plan validates chosen geography at creation',async()=>{const f=fixture();const result=await f.run('plan',{description:'Offer campaign in Belem for site.'});await assert.rejects(f.run('create',f.draft({location:result.draft.location,countries:['US']})),/Confira/);assert.equal(f.calls.length,0)});