const {test}=require('node:test'),assert=require('node:assert/strict'),{Readable}=require('node:stream'),crypto=require('node:crypto');
const {createCampaignManager,draftFromVideoAnalysis}=require('../Dashboard Meta Ads/campaign-manager');
test('browser multipart uploads preserve binary bytes and return an account-scoped media key',async()=>{
 for(const [type,hex] of [['image/png','89504e470d0a1a0a00ff000d0a'],['video/mp4','00000018667479706d703432000000006d70343269736f6d00ff0d0a']]){
  const f=fixture(),bytes=Buffer.from(hex,'hex'),form=new FormData();form.append('file',new Blob([bytes],{type}),'creative.'+(type==='video/mp4'?'mp4':'png'));
  const request=new Request('https://test/api/ads-manager/upload?account=act_111',{method:'POST',body:form});
  const req=Object.assign(Readable.fromWeb(request.body),{method:'POST',headers:Object.fromEntries(request.headers)});
  const result=await f.api.handle(req,{id:'a'},new URL(request.url));assert.ok(result.key);assert.equal(f.calls.length,1);
  const sent=type==='video/mp4'?Buffer.from(await f.calls[0].params.get('source').arrayBuffer()):Buffer.from(f.calls[0].params.bytes,'base64');assert.deepEqual(sent,bytes);
  assert.equal(f.store.get('ads-media:a').at(-1).account,'act_111');assert.equal(f.store.get('ads-media:b'),undefined);
 }
});
test('50 MB multipart upload survives a real local HTTP request without sending media to Meta',async()=>{
 const http=require('node:http'),f=fixture(),bytes=Buffer.alloc(51858487,90);Buffer.from('00000018667479706d703432000000006d70343269736f6d','hex').copy(bytes);
 const server=http.createServer(async(req,res)=>{try{const result=await f.api.handle(req,{id:'a'},new URL(req.url,'http://localhost'));res.writeHead(200,{'Content-Type':'application/json'});res.end(JSON.stringify(result))}catch(e){res.writeHead(e.status||500);res.end(e.message)}});
 await new Promise(resolve=>server.listen(0,'127.0.0.1',resolve));
 try{const form=new FormData();form.append('file',new Blob([bytes],{type:'video/mp4'}),'synthetic.mp4');const response=await fetch('http://127.0.0.1:'+server.address().port+'/api/ads-manager/upload?account=act_111',{method:'POST',body:form});assert.equal(response.status,200);assert.ok((await response.json()).key);assert.deepEqual(Buffer.from(await f.calls[0].params.get('source').arrayBuffer()),bytes)}finally{server.closeAllConnections();await new Promise(resolve=>server.close(resolve))}
});
test('chunked endpoints assemble the exact video and reuse final confirmation',async()=>{
 const f=fixture(),bytes=Buffer.alloc(3*1024*1024+5,122);Buffer.from('00000018667479706d703432','hex').copy(bytes);
 const session=await f.run('upload-start',{size:bytes.length,type:'video/mp4'});
 for(let offset=0;offset<bytes.length;offset+=session.chunkSize){const form=new FormData();form.append('upload',session.upload);form.append('offset',offset);form.append('file',new Blob([bytes.subarray(offset,offset+session.chunkSize)]),'part');const request=new Request('https://test/api/ads-manager/upload-part?account=act_111',{method:'POST',body:form});const req=Object.assign(Readable.fromWeb(request.body),{method:'POST',headers:Object.fromEntries(request.headers)});const result=await f.api.handle(req,{id:'a'},new URL(request.url));assert.equal(result.received,Math.min(offset+session.chunkSize,bytes.length))}
 const result=await f.run('upload-finish',{upload:session.upload});assert.equal(result.kind,'video');assert.deepEqual(await f.run('upload-finish',{upload:session.upload}),result);assert.equal(f.calls.length,1);assert.deepEqual(Buffer.from(await f.calls[0].params.get('source').arrayBuffer()),bytes);
});
function fixture(options={}){
 const store=new Map(),calls=[],graphs=[],nodes=new Map();let sequence=100,revision='one';
 const sourceAds=options.sourceAds===undefined?[{creative:{object_story_spec:{page_id:'1',link_data:{call_to_action:{value:{link:'https://wa.me/5594999999999'}}}}}}]:options.sourceAds;
 const user={id:'a'},conn={token:'private-test-token',revision:'one',scopes:options.readOnly?['ads_read']:['ads_read','ads_management']};
 const graph=async(token,object)=>{graphs.push(object);
  if(options.graphFailure&&object==='search')throw new Error('Meta indisponível para geolocalização');
  if(object==='act_111/ads')return {data:options.sourceAds||[]};
  if(object==='search')return {data:[{key:'city1',type:'city',name:'Belém',country_code:'BR',region:'Pará'}]};
  if(options.pageWabaUnavailable&&(object==='1'||object==='1/whatsapp_business_account'))throw new Error('Campo WABA indisponível');
  if(object==='1')return {whatsapp_business_account:{id:'waba-1',phone_numbers:{data:[{id:'phone-1',display_phone_number:'+55 94 99999-9999',verified_name:'Atendimento'}]}}};
  if(object==='777')return {status:{video_status:options.videoError?'error':options.processing?'processing':'ready'}};
  return nodes.get(object)||{id:object,account_id:object==='999'?'222':'111',campaign_id:'10',destination_type:options.existingDestination||'WEBSITE',promoted_object:{page_id:'1'},status:'PAUSED',effective_status:'PAUSED'};
 };
 const rows=async(token,edge,params={})=>edge.endsWith('/promote_pages')?[{id:'1',name:'Page'}]:edge==='act_111/ads'&&String(params.fields||'').includes('object_story_spec')?sourceAds:edge==='900/owned_whatsapp_business_accounts'||edge==='900/client_whatsapp_business_accounts'?(options.businessWabas===undefined?[{id:'waba-1'}]:options.businessWabas):edge.endsWith('/whatsapp_business_accounts')?(options.accountWabas||[]):edge==='waba-1/phone_numbers'?[{id:'phone-1',display_phone_number:'+55 94 99999-9999',verified_name:'Atendimento'}]:edge.endsWith('/instagram_accounts')?[{id:'2',username:'ig'}]:edge.endsWith('/leadgen_forms')?[{id:'3',status:'ACTIVE'}]:edge.endsWith('/thumbnails')?[{uri:'https://example.test/thumb.jpg'}]:[...nodes.values()].filter(x=>edge.endsWith('/'+x.edge));
 const api=createCampaignManager({graph,rows,analyzeVideo:options.videoAnalysis,planCampaign:options.planner|| (async()=>({name:"AI draft",headline:"Title",message:"Copy",dailyBudget:30,category:"",rationale:"Suggestion",destination:"site",locationQuery:"Bel?m",ageMin:18,ageMax:65,interestQueries:[],placements:"automatic"})),authorizeAccounts:async(u,ids)=>{if(ids[0]!=='act_111')throw Object.assign(new Error('Account denied'),{status:403});return {conn,accounts:[{id:'act_111',currency:'BRL',business:{id:'900'}}]}},connection:()=>({...conn,revision}),read:(k,u)=>store.get(k+':'+u),write:(k,u,v)=>store.set(k+':'+u,v),fetchImpl:async(url,opts)=>{const endpoint=url.pathname.split('/').slice(2).join('/'),params=opts.body instanceof URLSearchParams?Object.fromEntries(opts.body):opts.body;calls.push({endpoint,params});assert.equal(opts.headers.Authorization,'Bearer private-test-token');if(options.failure&&endpoint.endsWith(options.failure))return {ok:false,json:async()=>({error:{error_user_msg:'Invalid targeting'}})};let payload;if(endpoint.endsWith('/adimages'))payload={images:{file:{hash:'image-hash'}}};else if(endpoint.endsWith('/advideos'))payload={id:'777'};else if(!endpoint.includes('/')){const item=nodes.get(endpoint);if(item){item.status=params.status;item.effective_status=params.status}payload={success:true}}else{const id=String(++sequence);nodes.set(id,{id,account_id:'111',name:params.name,status:params.status,effective_status:params.status,edge:endpoint.split('/')[1]});payload={id}}if(options.changeConnection)revision='two';return {ok:true,json:async()=>payload}}});
 const run=(action,p,who=user,account='act_111')=>api.handle(Object.assign(Readable.from(p?[Buffer.from(JSON.stringify(p))]:[]),{method:p?'POST':'GET'}),who,new URL('https://test/api/ads-manager/'+action.replace('&','?')+(action.includes('&')?'&':'?')+'account='+account));
 const draft=(extra={})=>({key:crypto.randomUUID(),confirm:true,name:'Campaign',headline:'Headline',message:'Ad text',destination:'site',url:'https://example.test',page:'1',media:'image',dailyBudget:'35.50',countries:['BR'],ageMin:18,ageMax:65,...extra});
 store.set('ads-media:a',[{key:'image',account:'act_111',kind:'image',value:'image-hash'},{key:'video',account:'act_111',kind:'video',value:'777'}]);
 return {run,draft,calls,graphs,store,nodes,api};
}
test('new site campaign creates all levels active, exact minor-unit budget and no token returned',async()=>{const f=fixture(),p=f.draft(),result=await f.run('create',p);assert.equal(result.state,'complete');assert.equal(f.calls.length,4);for(const c of f.calls.filter(x=>!x.endpoint.endsWith('adcreatives')))assert.equal(c.params.status,'ACTIVE');assert.equal(f.calls[1].params.daily_budget,'3550');assert.equal(f.calls[0].params.objective,'OUTCOME_TRAFFIC');assert.ok(!JSON.stringify(result).includes('private-test-token'));assert.deepEqual(await f.run('create',p),result);assert.equal(f.calls.length,4)});
test('WhatsApp and lead forms use their own objectives, destinations and CTAs',async()=>{for(const destination of ['whatsapp','form']){const f=fixture();await f.run('create',f.draft({destination,phone:'5594999999999',form:'3',instagram:'2'}));assert.equal(f.calls[0].params.objective,destination==='form'?'OUTCOME_LEADS':'OUTCOME_ENGAGEMENT');assert.equal(f.calls[1].params.destination_type,destination==='form'?'ON_AD':'WHATSAPP');const story=JSON.parse(f.calls[2].params.object_story_spec);assert.equal(story.instagram_user_id,'2');assert.equal(story.link_data.call_to_action.type,destination==='form'?'SIGN_UP':'WHATSAPP_MESSAGE')}});
test('WhatsApp assets expose only a Page-linked number, avoid removed Graph fields, and reject an arbitrary number',async()=>{const f=fixture(),assets=await f.run('assets');assert.deepEqual(assets.whatsapps,[{id:'phone-1',phone:'5594999999999',label:'Atendimento',pageId:'1',pageName:'Page',businessId:'waba-1'}]);assert.ok(!f.graphs.some(endpoint=>endpoint==='1'||endpoint==='1/whatsapp_business_account'||endpoint==='act_111/whatsapp_business_accounts'));await assert.rejects(f.run('create',f.draft({destination:'whatsapp',phone:'5511999999999'})),/não está vinculado/)});
test('WhatsApp discovery combines the Page WABA with the authorized BM WABA before offering its number',async()=>{const allowed=fixture({businessWabas:[{id:'waba-1'}]}),ready=await allowed.run('whatsapps');assert.equal(ready.state,'ready');assert.equal(ready.items[0].phone,'5594999999999');const other=fixture({businessWabas:[{id:'waba-other'}]}),empty=await other.run('whatsapps');assert.equal(empty.state,'empty');assert.equal(empty.items.length,0)});
test('WhatsApp discovery keeps a Page-approved number selectable when the WABA Page field is unavailable',async()=>{const f=fixture({pageWabaUnavailable:true,sourceAds:[{creative:{object_story_spec:{page_id:'1',link_data:{call_to_action:{value:{link:'https://wa.me/5594999999999'}}}}}}]}),result=await f.run('whatsapps');assert.equal(result.state,'ready');assert.deepEqual(result.items.map(item=>item.phone),['5594999999999']);await f.run('create',f.draft({destination:'whatsapp',phone:'5594999999999'}));assert.equal(f.calls[0].endpoint,'act_111/campaigns')});
test('video analysis builds the established safe copy structure without monetary values',()=>{const draft=draftFromVideoAnalysis({offer:'Crédito imobiliário por R$ 25.795,20',transcript:'Fale com nossa equipe em Rio Branco',visibleText:['Aprovação rápida','Parcelas de R$ 999'],benefits:['Sem burocracia','Condições flexíveis'],location:'Rio Branco, Acre',destination:'whatsapp',audience:{ageMin:20,ageMax:45},cta:'Clique no WhatsApp'});assert.equal(draft.dailyBudget,1);assert.equal(draft.destination,'whatsapp');assert.equal(draft.locationQuery,'Rio Branco, Acre');assert.match(draft.message,/^🏠 /);assert.equal((draft.message.match(/^✅ /gm)||[]).length,3);assert.match(draft.message,/^📲 /m);assert.doesNotMatch(draft.message,/(?:R\$|parcelas|valor|entrada)/i)});
test('video analysis still opens review when Meta cannot resolve the suggested location',async()=>{
 const f=fixture({graphFailure:true,videoAnalysis:async()=>({offer:'Casa nova',transcript:'Fale pelo WhatsApp',visibleText:[],location:'Rio Branco, Acre',destination:'whatsapp',audience:{gender:'all',ageMin:20,ageMax:45},cta:'Chame no WhatsApp',confidence:'high'})});
 const bytes=Buffer.from('00000018667479706d703432000000006d70343269736f6d','hex'),form=new FormData();form.append('file',new Blob([bytes],{type:'video/mp4'}),'creative.mp4');
 const request=new Request('https://test/api/ads-manager/analyze?account=act_111',{method:'POST',body:form}),req=Object.assign(Readable.fromWeb(request.body),{method:'POST',headers:Object.fromEntries(request.headers)});
 const result=await f.api.handle(req,{id:'a'},new URL(request.url));assert.equal(result.reviewRequired,true);assert.deepEqual(result.draft.location,{key:'BR',type:'country',name:'Brasil',country:'BR',region:''});assert.equal(result.draft.locationQuery,'Brasil');assert.equal(result.draft.destination,'whatsapp');
});
test('existing compatible adset creates the creative and active ad',async()=>{const f=fixture();await f.run('create',f.draft({adset:'11'}));assert.equal(f.calls.length,2);assert.equal(f.calls[1].params.adset_id,'11');assert.equal(f.calls[1].params.status,'ACTIVE')});
test('rejects wrong account, missing write permission, foreign page, Instagram and media',async()=>{const f=fixture();await assert.rejects(f.run('create',f.draft(),{id:'a'},'act_222'),/denied/);await assert.rejects(f.run('create',f.draft({page:'9'})),/Página/);await assert.rejects(f.run('create',f.draft({instagram:'9'})),/Instagram/);await assert.rejects(f.run('create',f.draft(),{id:'b'}),/criativo/);const readOnly=fixture({readOnly:true});await assert.rejects(readOnly.run('create',readOnly.draft()),/gerenciamento/);assert.equal(f.calls.length,0);assert.equal(readOnly.calls.length,0)});
test('rejects foreign or incompatible adsets and inactive/foreign lead forms before mutation',async()=>{const f=fixture();for(const p of [f.draft({adset:'999'}),f.draft({adset:'11',destination:'whatsapp',phone:'5594999999999'}),f.draft({destination:'form',form:'9'})])await assert.rejects(f.run('create',p));assert.equal(f.calls.length,0)});
test('partial failure records created IDs and blocks retry of the same operation',async()=>{const f=fixture({failure:'adsets'}),p=f.draft();await assert.rejects(f.run('create',p),/Invalid targeting/);const result=await f.run('operations');assert.equal(result.items[0].state,'needs_review');assert.equal(result.items[0].created.campaign,'101');await assert.rejects(f.run('create',p),/registrada/);assert.equal(f.calls.length,2)});
test('video waits for readiness; ready video uses the thumbnail and video creative',async()=>{const pending=fixture({processing:true});await assert.rejects(pending.run('create',pending.draft({media:'video'})),/processado/);assert.equal(pending.calls.length,0);const f=fixture();await f.run('create',f.draft({media:'video'}));assert.equal(JSON.parse(f.calls[2].params.object_story_spec).video_data.video_id,'777')});
test('explicit status confirmation and exact typed account edge are required',async()=>{const f=fixture();const r=await f.run('create',f.draft());await assert.rejects(f.run('status',{kind:'ad',id:r.created.campaign,status:'ACTIVE',confirm:true}),/autorizado/);await assert.rejects(f.run('status',{kind:'ad',id:r.created.ad,status:'ACTIVE'}),/Confirme/);const result=await f.run('status',{kind:'ad',id:r.created.ad,status:'ACTIVE',confirm:true});assert.equal(result.item.status,'ACTIVE')});
test('upload checks actual file signature and scopes, then registers media per user/account',async()=>{const f=fixture();await assert.rejects(f.run('upload',{type:'image/png',data:Buffer.from('not a png').toString('base64')}),/conteúdo/);const result=await f.run('upload',{type:'image/png',data:Buffer.from('89504e470d0a1a0a','hex').toString('base64')});assert.equal(result.kind,'image');assert.equal(f.store.get('ads-media:a').at(-1).account,'act_111');assert.equal(f.store.get('ads-media:b'),undefined)});
test('connection change stops further writes and leaves an operation requiring review',async()=>{const f=fixture({changeConnection:true});await assert.rejects(f.run('create',f.draft()),/conexão mudou/);assert.equal(f.calls.length,1);assert.equal((await f.run('operations')).items[0].state,'needs_review')});
test('invalid budget and URL cannot create any objects; special categories use broad age range',async()=>{const f=fixture();await assert.rejects(f.run('create',f.draft({dailyBudget:-1})));await assert.rejects(f.run('create',f.draft({url:'javascript:alert(1)'})));assert.equal(f.calls.length,0);await f.run('create',f.draft({category:'HOUSING',ageMin:25,ageMax:40}));const t=JSON.parse(f.calls[1].params.targeting);assert.equal(t.age_min,18);assert.equal(t.age_max,65)});

test('quick planning uses authorized assets and verified geography without creating ads',async()=>{const f=fixture();const locations=await f.run('locations&q=Be');const location=locations.items[0];const result=await f.run('plan',{description:'Quero uma campanha de consultoria em Belem pelo WhatsApp, R$ 40 por dia, 25 a 45 anos no Facebook e Instagram.'});assert.equal(result.reviewRequired,true);assert.equal(result.draft.location.name,'Belém');assert.equal(f.calls.length,0);await f.run('create',f.draft({location:result.draft.location}));assert.deepEqual(JSON.parse(f.calls[1].params.targeting).geo_locations,{cities:[{key:'city1'}]});});


test('JPEG and MP4 uploads use the correct Meta transport and preserve media ownership',async()=>{for(const [type,data,kind] of [['image/jpeg','ffd8ffe000104a464946','image'],['video/mp4','00000018667479706d703432000000006d70343269736f6d','video']]){const f=fixture();const result=await f.run('upload',{type,data:Buffer.from(data,'hex').toString('base64')});assert.equal(result.kind,kind);const call=f.calls[0];assert.equal(call.endpoint,kind==='image'?'act_111/adimages':'act_111/advideos');if(kind==='video'){const file=call.params.get('source');assert.equal(file.type,'video/mp4');assert.equal(file.name,'creative.mp4');assert.deepEqual(Buffer.from(await file.arrayBuffer()),Buffer.from(data,'hex'));}assert.equal(f.store.get('ads-media:a').at(-1).account,'act_111');}});
test('oversized and mismatched files cannot reach Meta; failed video does not create campaigns',async()=>{const f=fixture();await assert.rejects(f.run('upload',{type:'image/jpeg',data:Buffer.alloc(100*1024*1024+1,255).toString('base64')}),/100 MB/);await assert.rejects(f.run('upload',{type:'video/mp4',data:Buffer.from('this is not an mp4').toString('base64')}),/formato/);assert.equal(f.calls.length,0);const failed=fixture({videoError:true});await assert.rejects(failed.run('create',failed.draft({media:'video'})),/outro MP4/);assert.equal(failed.calls.length,0);});

test('intelligent planning requires a meaningful description and does not create ads',async()=>{const f=fixture();await assert.rejects(f.run('plan',{description:'short'}),/12 a 1500/);assert.equal(f.calls.length,0)});
test('intelligent plan validates chosen geography at creation',async()=>{const f=fixture();const result=await f.run('plan',{description:'Campanha em Belem para site, R$ 40 por dia, 25 a 45 anos, Facebook e Instagram.'});await assert.rejects(f.run('create',f.draft({location:{...result.draft.location,key:'unknown'},countries:['BR']})),/localiza/);assert.equal(f.calls.length,0)});
test('special-category city targeting includes the minimum radius required by Meta',async()=>{const f=fixture();const result=await f.run('plan',{description:'Campanha em Belem para site, R$ 40 por dia, 25 a 45 anos, Facebook e Instagram.'});await f.run('create',f.draft({location:result.draft.location,category:'FINANCIAL_PRODUCTS_SERVICES'}));assert.deepEqual(JSON.parse(f.calls[1].params.targeting).geo_locations,{cities:[{key:'city1',radius:17,distance_unit:'kilometer'}]});});
