const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),os=require('node:os'),path=require('node:path'),{spawn}=require('node:child_process');
test('local workflows persist and stay isolated across users',async t=>{
 const dir=fs.mkdtempSync(path.join(os.tmpdir(),'hurtz-local-test-')),root=path.resolve(__dirname,'..');
 const child=spawn(process.execPath,['--require',path.join(__dirname,'local-providers.cjs'),path.join(root,'dev/local-server.cjs')],{env:{...process.env,PORT:'8093',LOCAL_DATA_DIR:dir},stdio:['ignore','pipe','pipe']});let logs='';child.stderr.on('data',c=>logs+=c);
 t.after(async()=>{child.kill();await new Promise(r=>child.once('close',r));fs.rmSync(dir,{recursive:true,force:true})});
 const base='http://localhost:8093';
 async function request(token,route,method='GET',payload){const r=await fetch(base+route,{method,headers:{'Content-Type':'application/json',...(token?{Authorization:'Bearer '+token}:{})},...(payload===undefined?{}:{body:JSON.stringify(payload)})});const text=await r.text();let body;try{body=JSON.parse(text)}catch{body=text}return {status:r.status,body}}
 for(let n=0;n<50;n++){try{if((await fetch(base)).ok)break}catch{}await new Promise(r=>setTimeout(r,100))}
 assert.equal((await request(null,'/api/tasks')).status,401);
 assert.equal((await fetch(base+'/api/local/session',{method:'POST',headers:{Origin:'https://evil.example','X-Local-Client':'1'}})).status,403);
 const signup=async email=>{const r=await request(null,'/api/auth/signup','POST',{email,password:'local-test-password'});assert.equal(r.status,200,JSON.stringify(r.body));return r.body.token};
 const a=await signup('a@example.test'),b=await signup('b@example.test');
 assert.equal((await request(null,'/api/auth/login','POST',{email:'a@example.test',password:'wrong-password'})).status,401);
 const tasks=await request(a,'/api/tasks');assert.equal(tasks.status,200,JSON.stringify(tasks.body));assert.equal(tasks.body.columns.length,3);
 const column=tasks.body.columns[0].id,otherColumn=(await request(b,'/api/tasks')).body.columns[0].id;
 assert.notEqual(column,otherColumn);
 const create=await request(a,'/api/tasks','POST',{title:'Private task',column_id:column});assert.equal(create.status,201,JSON.stringify(create.body));const id=create.body.id;
 assert.equal((await request(b,'/api/tasks')).body.tasks.length,0);
 assert.notEqual((await request(b,'/api/tasks','PUT',{id,title:'steal'})).status,200);
 assert.notEqual((await request(b,'/api/tasks','POST',{title:'foreign',column_id:column})).status,201);
 const sub=await request(a,'/api/task-subtasks','POST',{task_id:id,title:'Checklist'});assert.equal(sub.status,201,JSON.stringify(sub.body));
 assert.equal((await request(a,'/api/task-comments','POST',{task_id:id,body:'Private note'})).status,201);
 const attachment=await request(a,'/api/task-attachments','POST',{task_id:id,file_name:'note.txt',mime_type:'text/plain',data:Buffer.from('private attachment').toString('base64')});
 assert.equal(attachment.status,201,JSON.stringify(attachment.body));
 assert.equal((await request(a,'/api/task-attachments?id='+attachment.body.id)).body,'private attachment');
 assert.notEqual((await request(b,'/api/task-attachments?id='+attachment.body.id)).status,200);
 const profile=await request(a,'/api/creative-search-settings','POST',{name:'Vehicles',terms:['HB20']});assert.equal(profile.status,201);
 assert.equal((await request(b,'/api/creative-search-settings')).body.presets.length,0);
 assert.equal((await request(a,'/api/creative-videos','POST',{videos:[{video_url:'https://www.tiktok.com/@test/video/12345',title:'Saved reference'}]})).status,201);
 assert.equal((await request(b,'/api/creative-videos')).body.videos.length,0);
 assert.equal((await request(a,'/api/creative-videos','POST',{videos:[{video_url:'javascript:alert(1)'}]})).status,400);
 assert.equal((await request(a,'/api/creative-videos','POST',{videos:[{video_url:'https://www.instagram.com/reel/ABCdef_123/'}]})).status,201);
 const settings=await request(a,'/api/local/settings','PUT',{apifyToken:'apify-private-test',evolutionUrl:'https://evolution.local.test',evolutionKey:'evolution-private-test'});assert.equal(settings.status,200);assert.equal(settings.body.apifyConfigured,true);assert.ok(!JSON.stringify(settings.body).includes('apify-private-test'));
 assert.equal((await request(b,'/api/local/settings')).body.apifyConfigured,false);
 assert.equal((await request(b,'/api/creative-search','POST',{terms:['HB20'],platform:'tiktok'})).status,503);
 const search=await request(a,'/api/creative-search','POST',{terms:['HB20'],platform:'tiktok',limit:1});assert.equal(search.status,200,JSON.stringify(search.body));assert.equal(search.body.approved.length,1);
 assert.equal((await request(b,'/api/creative-audit/status?id='+search.body.id)).status,404);
 assert.equal((await request(b,search.body.approved[0].download_url)).status,404);
 assert.equal((await request(a,search.body.approved[0].download_url)).status,200);
 const access=(await request(a,'/api/local/access','POST',{scope:'extension'})).body;
 assert.equal((await request(access.token,'/api/tasks')).status,403);
 assert.equal((await request(access.token,'/api/creative-videos')).body.videos.length,2);
 await request(a,'/api/local/settings','PUT',{visualAudit:true});await request(b,'/api/local/settings','PUT',{visualAudit:true,apifyToken:'apify-b-test'});
 for(const user of [a,b]){
  assert.equal((await request(user,'/api/local/settings')).body.visualAudit,false);
  const result=await request(user,'/api/creative-search','POST',{terms:['HB20'],platform:'tiktok',limit:1});
  assert.equal(result.status,200);assert.equal(result.body.status,'complete');assert.equal(result.body.approved.length,1);
  const resumed=await request(user,'/api/creative-audit/status?id='+result.body.id);
  assert.equal(resumed.body.status,'complete');assert.equal(resumed.body.approved.length,1);assert.equal(resumed.body.visual_audit_enabled,false);
  assert.equal((await request(user===a?b:a,'/api/creative-audit/status?id='+result.body.id)).status,404);
 }
 const instance=(await request(a,'/api/evolution/instance','POST',{label:'Local'})).body.instance;assert.ok(instance);
 assert.equal((await request(b,'/api/evolution/groups?instance='+instance)).status,403);
 assert.equal((await request(a,'/api/evolution/groups?instance='+instance)).body.groups.length,1);
 const c={enabled:false,dry_run:true,thresholds:[75,100],quiet_start:'21:00',quiet_end:'07:00',daily_summary_time:'19:30',performance_report_time:'08:30',evolution_instance:instance,evolution_group_jid:'123@g.us'};
 assert.equal((await request(a,'/api/alerts/config','PUT',c)).status,200);
 assert.equal((await request(b,'/api/alerts')).body.config.evolution_instance,undefined);
 assert.equal((await request(a,'/api/alerts/run','POST',{})).body.enabled,false);
 const connect=async(token,fb)=>{const nonce=(await request(token,'/api/meta/challenge','POST',{})).body.nonce;const r=await request(token,'/api/meta/connection','POST',{nonce,accessToken:fb});assert.equal(r.status,200,JSON.stringify(r.body))};
 await connect(a,'facebook-a-token-0000000000');await connect(b,'facebook-b-token-0000000000');
 await connect(a,'facebook-a-limited-0000000000');assert.ok((await request(a,'/api/meta-comment-pages')).body.missingPermissions.includes('pages_manage_engagement'));assert.equal((await request(a,'/api/meta-comments?page=100&status=active&days=30')).status,403);await connect(a,'facebook-a-token-0000000000');
 const pages=await request(a,'/api/meta-comment-pages');assert.deepEqual(new Set(pages.body.pages.map(p=>p.id)),new Set(['100','300','500']));assert.deepEqual(pages.body.missingPermissions,[]);assert.equal(JSON.stringify(pages.body).includes('access_token'),false);
 assert.equal((await request(b,'/api/meta-comments?page=100&status=active&days=30')).status,403);
 assert.equal((await request(a,'/api/meta-comments?page=300&status=active&days=30')).body.comments,0);
 assert.equal((await request(a,'/api/meta-comments?page=100&status=active&days=30')).body.comments,1);
 const comments=await request(a,'/api/meta-comments?accounts=act_111&status=active&days=30');assert.equal(comments.status,200);assert.equal(comments.body.comments,1);
 assert.equal((await request(b,'/api/meta-comments','POST',{action:'hide',comment_ids:['100_1001']})).status,403);
 assert.equal((await request(a,'/api/meta-comments','POST',{action:'hide',comment_ids:['100_1001']})).body.success,1);
 assert.equal((await request(b,'/api/meta-comment-history')).body.events.length,0);
 await request(a,'/api/meta/connection','DELETE');assert.equal((await request(a,'/api/meta-comments','POST',{action:'hide',comment_ids:['100_1001']})).status,409);
 assert.equal((await request(a,'/api/tasks')).body.tasks.length,1,'Facebook disconnect must not delete local work');
 const login=await request(null,'/api/auth/login','POST',{email:'a@example.test',password:'local-test-password'});assert.equal((await request(login.body.token,'/api/tasks')).body.tasks.length,1);
 assert.equal((await request(a,'/api/tasks?id='+id,'DELETE')).status,200);
 assert.equal((await request(a,'/api/tasks')).body.subtasks.length,0);
 await request(a,'/api/session','DELETE');assert.equal((await request(a,'/api/tasks')).status,401);
 for(const file of fs.readdirSync(dir).filter(f=>f.endsWith('.json'))){const text=fs.readFileSync(path.join(dir,file),'utf8');assert.ok(!text.includes('apify-private-test')&&!text.includes('facebook-a-token')&&!text.includes('local-test-password'))}
 assert.equal(logs.includes('TypeError'),false,logs);
});
