import React from 'react';
import {AbsoluteFill,Audio,Easing,OffthreadVideo,Sequence,interpolate,staticFile,useCurrentFrame} from 'remotion';

const NAVY='#071d2d',NAVY2='#0d3045',GREEN='#087f68',MINT='#45d3b0',CREAM='#f5f1e8',RED='#bd2437';
const f=(s:number)=>Math.round(s*30);
type Cue={s:number;e:number;t:string;hi?:string[]};
const CUES:Cue[]=[
  {s:f(32.32),e:f(34.70),t:'É TOMADA DE DECISÕES\nESTRATÉGICAS.',hi:['TOMADA','DECISÕES','ESTRATÉGICAS']},
  {s:f(34.88),e:f(35.63),t:'De forma LEGAL.',hi:['LEGAL']},
  {s:f(35.91),e:f(39.00),t:'Para sua empresa não pagar mais\nIMPOSTO DO QUE DEVERIA.',hi:['IMPOSTO','DEVERIA']},
];

const CityTag=()=> <div style={{position:'absolute',top:470,right:46,background:RED,color:'#fff',padding:'15px 23px',font:'900 32px Arial',letterSpacing:.6,boxShadow:'0 6px 16px rgba(0,0,0,.25)'}}>PARAUAPEBAS</div>;

const Caption=({cue}:{cue:Cue})=>{const frame=useCurrentFrame();const local=frame-cue.s;const out=interpolate(frame,[cue.e-8,cue.e],[0,1],{extrapolateLeft:'clamp',extrapolateRight:'clamp',easing:Easing.in(Easing.cubic)});return <div style={{font:'900 61px/1.1 Arial',color:'#fff',whiteSpace:'pre-line',textAlign:'center',textShadow:'0 5px 11px rgba(0,0,0,.82)',opacity:1-out,filter:`blur(${out*10}px)`,transform:`translateY(${-out*14}px)`}}>{cue.t.split(/(\s+)/).map((w,i)=>{if(/^\s+$/.test(w))return w;const p=interpolate(local,[Math.min(i*.75,8),Math.min(i*.75,8)+11],[0,1],{extrapolateLeft:'clamp',extrapolateRight:'clamp',easing:Easing.out(Easing.cubic)});const clean=w.replace(/[^A-ZÁÉÍÓÚÃÕÇ]/g,'');const hi=cue.hi?.includes(clean);return <span key={i} style={{display:'inline-block',color:hi?MINT:'#fff',opacity:p,filter:`blur(${(1-p)*10}px)`,transform:`translateY(${(1-p)*26}px)`}}>{w}</span>})}</div>};

const charY=(frame:number,i:number,start=7)=>{const t=start+i*2;if(frame<t+14)return interpolate(frame,[t,t+14],[115,-10],{extrapolateLeft:'clamp',extrapolateRight:'clamp',easing:Easing.out(Easing.cubic)});return interpolate(frame,[t+14,t+20],[-10,0],{extrapolateLeft:'clamp',extrapolateRight:'clamp',easing:Easing.out(Easing.quad)})};
const SplitWord=({word,frame,color,size=150,start=7}:{word:string;frame:number;color:string;size?:number;start?:number})=><div style={{display:'flex',justifyContent:'center'}}>{word.split('').map((c,i)=><div key={i} style={{overflow:'hidden',height:size*1.35,display:'flex',alignItems:'flex-end'}}><span style={{font:`900 ${size}px/1 Arial`,color,display:'inline-block',transform:`translateY(${charY(frame,i,start)}%)`}}>{c===' '?' ':c}</span></div>)}</div>;

const TimedHookLine=({start,end,children}:{start:number;end:number;children:React.ReactNode})=>{const frame=useCurrentFrame();const enter=interpolate(frame,[start,start+8],[0,1],{extrapolateLeft:'clamp',extrapolateRight:'clamp',easing:Easing.out(Easing.cubic)});const exit=interpolate(frame,[end-7,end],[0,1],{extrapolateLeft:'clamp',extrapolateRight:'clamp',easing:Easing.in(Easing.cubic)});return <div style={{position:'absolute',left:55,right:55,top:1640,textAlign:'center',font:'900 67px/1.05 Arial',color:'#fff',textShadow:'0 5px 11px rgba(0,0,0,.82)',opacity:enter*(1-exit),filter:`blur(${(1-enter)*12+exit*10}px)`,transform:`translateY(${(1-enter)*38-exit*15}px)`}}>{children}</div>};
const Hook=()=> <div style={{position:'absolute',inset:0,fontFamily:'Arial'}}><TimedHookLine start={2} end={58}>MUITOS <span style={{color:MINT}}>EMPRESÁRIOS</span></TimedHookLine><TimedHookLine start={59} end={114}>PAGAM IMPOSTOS<br/><span style={{color:MINT}}>TODO MÊS</span></TimedHookLine><TimedHookLine start={118} end={166}>SEM SABER SE ESTÃO<br/><span style={{color:RED}}>REALMENTE...</span></TimedHookLine><TimedHookLine start={166} end={248}>NO REGIME TRIBUTÁRIO<br/><span style={{color:MINT}}>MAIS ADEQUADO?</span></TimedHookLine></div>;

const PlanningTitle=()=>{const frame=useCurrentFrame()-248;const line=interpolate(frame,[7,36],[0,100],{extrapolateLeft:'clamp',extrapolateRight:'clamp',easing:Easing.out(Easing.cubic)});return <AbsoluteFill style={{background:`linear-gradient(150deg,${NAVY},${NAVY2})`,fontFamily:'Arial',color:'#fff',alignItems:'center',justifyContent:'center'}}><div style={{font:'800 34px Arial',letterSpacing:8,color:'#8bb4c5',marginBottom:35}}>É AQUI QUE ENTRA O</div><SplitWord word="PLANEJAMENTO" frame={frame} color="#fff" size={112}/><SplitWord word="TRIBUTÁRIO" frame={frame-8} color={MINT} size={132}/><div style={{height:6,width:`${Math.min(80,line)}%`,background:GREEN,marginTop:35}}/></AbsoluteFill>};

const FactorList=()=>{const frame=useCurrentFrame()-332;const items=[['FATURAMENTO',20],['FOLHA DE PAGAMENTO',68],['ATIVIDADE EXERCIDA',111],['CUSTOS',165],['PARTICULARIDADES',199]] as const;const phase=frame<266?0:frame<340?1:frame<403?2:3;const footer=['','COMPARAR CENÁRIOS','IDENTIFICAR OPORTUNIDADES','ECONOMIA DENTRO DA LEGISLAÇÃO'][phase];const phaseStart=[0,266,340,403][phase];const fp=interpolate(frame,[phaseStart,phaseStart+10],[0,1],{extrapolateLeft:'clamp',extrapolateRight:'clamp',easing:Easing.out(Easing.cubic)});return <AbsoluteFill style={{background:`linear-gradient(145deg,${CREAM},#dce9e5)`,fontFamily:'Arial',color:NAVY,alignItems:'center',justifyContent:'center'}}><div style={{position:'absolute',top:465,font:'900 51px Arial',letterSpacing:3,color:GREEN}}>O QUE É ANALISADO?</div><div style={{display:'flex',flexDirection:'column',gap:28,transform:`translateY(${interpolate(frame,[0,470],[18,-18])}px)`}}>{items.map(([s,start],i)=>{const p=interpolate(frame,[start,start+18],[0,1],{extrapolateLeft:'clamp',extrapolateRight:'clamp',easing:Easing.out(Easing.back(1.08))});return <div key={s} style={{width:1030,padding:'28px 40px',background:'rgba(255,255,255,.74)',borderLeft:`10px solid ${GREEN}`,fontSize:52,fontWeight:900,opacity:Math.min(1,p*2.2),transform:`scale(${.78+p*.22}) translateY(${(1-p)*14}px)`,boxShadow:'0 10px 24px rgba(7,29,45,.1)'}}>{String(i+1).padStart(2,'0')}  {s}</div>})}</div>{footer&&<div key={footer} style={{position:'absolute',bottom:480,left:40,right:40,textAlign:'center',font:'900 43px Arial',color:GREEN,opacity:fp,filter:`blur(${(1-fp)*8}px)`,transform:`translateY(${(1-fp)*20}px)`}}>{footer}</div>}</AbsoluteFill>};

const angleAt=(frame:number,i:number)=>{const s=18+i*13;if(frame<s+18)return interpolate(frame,[s,s+18],[0,192],{extrapolateLeft:'clamp',extrapolateRight:'clamp',easing:Easing.bezier(.55,0,.3,1)});return interpolate(frame,[s+18,s+26],[192,180],{extrapolateLeft:'clamp',extrapolateRight:'clamp',easing:Easing.out(Easing.poly(5))})};
const FlipCard=({i,front,back,frame}:{i:number;front:string;back:string;frame:number})=>{const angle=angleAt(frame,i);return <div style={{width:560,height:360,perspective:1200}}><div style={{width:'100%',height:'100%',position:'relative',transformStyle:'preserve-3d',transform:`rotateY(${angle}deg)`}}><div style={{position:'absolute',inset:0,backfaceVisibility:'hidden',borderRadius:24,background:'#fff',border:`3px solid ${RED}`,display:'flex',alignItems:'center',justifyContent:'center',textAlign:'center',font:'900 55px/1.05 Arial',color:NAVY,boxShadow:'0 18px 35px rgba(0,0,0,.14)'}}>{front}</div><div style={{position:'absolute',inset:0,backfaceVisibility:'hidden',transform:'rotateY(180deg)',borderRadius:24,background:NAVY,border:`3px solid ${GREEN}`,display:'flex',alignItems:'center',justifyContent:'center',textAlign:'center',font:'900 69px/1.02 Arial',color:MINT,boxShadow:'0 18px 35px rgba(0,0,0,.2)'}}>{back}</div></div></div>};
const StrategicFlip=()=>{const frame=useCurrentFrame()-803;const p=interpolate(frame,[62,92],[0,1],{extrapolateLeft:'clamp',extrapolateRight:'clamp',easing:Easing.out(Easing.cubic)});return <AbsoluteFill style={{background:`linear-gradient(145deg,${CREAM},#e2ebe8)`,fontFamily:'Arial',alignItems:'center',justifyContent:'center'}}><div style={{position:'absolute',top:450,font:'900 49px Arial',color:RED,letterSpacing:3}}>PLANEJAMENTO TRIBUTÁRIO</div><div style={{display:'flex',gap:55}}><FlipCard i={0} front="SONEGAÇÃO" back="NÃO" frame={frame}/><FlipCard i={1} front={'SÓ O IMPOSTO\nMAIS BARATO'} back={'NÃO É\nSÓ ISSO'} frame={frame}/></div><div style={{position:'absolute',top:1510,left:90,right:90,textAlign:'center',opacity:p,filter:`blur(${(1-p)*10}px)`,transform:`translateY(${(1-p)*30}px)`,font:'900 66px/1.05 Arial',color:NAVY}}>É DECISÃO <span style={{color:GREEN}}>ESTRATÉGICA</span><br/>E DENTRO DA LEI</div></AbsoluteFill>};

const CtaStage=({start,end,children}:{start:number;end:number;children:React.ReactNode})=>{const frame=useCurrentFrame()-1177;const p=interpolate(frame,[start,start+7],[0,1],{extrapolateLeft:'clamp',extrapolateRight:'clamp',easing:Easing.out(Easing.cubic)});const out=interpolate(frame,[end-6,end],[0,1],{extrapolateLeft:'clamp',extrapolateRight:'clamp',easing:Easing.in(Easing.cubic)});return <div style={{position:'absolute',left:70,right:70,top:870,textAlign:'center',font:'900 92px/1 Arial',opacity:p*(1-out),filter:`blur(${(1-p)*12+out*9}px)`,transform:`translateY(${(1-p)*42-out*15}px)`}}>{children}</div>};
const FinalCTA=()=>{const frame=useCurrentFrame()-1177;const btn=interpolate(frame,[126,133,140],[1,1.12,1],{extrapolateLeft:'clamp',extrapolateRight:'clamp',easing:Easing.out(Easing.cubic)});const glow=interpolate(frame,[126,137],[0,1],{extrapolateLeft:'clamp',extrapolateRight:'clamp'});return <AbsoluteFill style={{background:`radial-gradient(circle at 50% 45%,#116052 0%,${NAVY} 58%,#04121c 100%)`,fontFamily:'Arial',color:'#fff',justifyContent:'center',alignItems:'center',textAlign:'center'}}><CtaStage start={0} end={34}>VOCÊ É<br/><span style={{color:MINT}}>EMPRESÁRIO?</span></CtaStage><CtaStage start={34} end={90}>QUER TOMAR<br/><span style={{color:MINT}}>DECISÕES TRIBUTÁRIAS?</span></CtaStage><CtaStage start={90} end={126}>COM<br/><span style={{color:MINT}}>ESTRATÉGIA?</span></CtaStage>{frame>=120&&<div style={{position:'absolute',top:1030,background:RED,color:'#fff',borderRadius:70,padding:'31px 110px',font:'900 72px Arial',transform:`scale(${btn})`,boxShadow:`0 0 ${25+glow*45}px rgba(189,36,55,${.35+glow*.35})`}}>ME SIGA</div>}<div style={{position:'absolute',bottom:520,font:'800 34px Arial',letterSpacing:6,color:'#9fc1cc'}}>CONTEÚDO TRIBUTÁRIO SEM COMPLICAÇÃO</div></AbsoluteFill>};

export const Integra02:React.FC=()=>{const frame=useCurrentFrame();const hook=frame<248,title=frame>=248&&frame<332,list=frame>=524&&frame<803,flip=frame>=803&&frame<970,cta=frame>=1176;const special=hook||title||list||flip||cta;return <AbsoluteFill style={{background:'#000'}}><OffthreadVideo src={staticFile('integra02.mp4')}/>{!special&&<><CityTag/><div style={{position:'absolute',left:70,right:70,top:1650,height:230,display:'flex',alignItems:'center',justifyContent:'center'}}>{CUES.filter(c=>frame>=c.s&&frame<c.e).map(c=><Caption key={c.s} cue={c}/>)}</div></>}{hook&&<><CityTag/><Hook/></>}{title&&<PlanningTitle/>}{list&&<FactorList/>}{flip&&<StrategicFlip/>}{cta&&<FinalCTA/>}
<Sequence from={7} durationInFrames={30}><Audio src={staticFile('sfx/transition-soft.mp3')} volume={.36}/></Sequence><Sequence from={248} durationInFrames={50}><Audio src={staticFile('sfx/transition-tech.mp3')} volume={.32}/></Sequence><Sequence from={524} durationInFrames={35}><Audio src={staticFile('sfx/transition-soft.mp3')} volume={.36}/></Sequence>{[542,572,602,632,662].map(x=><Sequence key={x} from={x} durationInFrames={22}><Audio src={staticFile('sfx/hitech-touch-magnet.mp3')} volume={.23}/></Sequence>)}<Sequence from={803} durationInFrames={38}><Audio src={staticFile('sfx/transition-tech.mp3')} volume={.32}/></Sequence>{[839,852].map(x=><Sequence key={x} from={x} durationInFrames={22}><Audio src={staticFile('sfx/pop-electric.mp3')} volume={.27}/></Sequence>)}<Sequence from={1176} durationInFrames={45}><Audio src={staticFile('sfx/impact-deep-whoosh.mp3')} volume={.34}/></Sequence></AbsoluteFill>};

export const Integra02Fixed:React.FC=()=>{const frame=useCurrentFrame();const hook=frame<248,title=frame>=248&&frame<332,list=frame>=332&&frame<803,flip=frame>=803&&frame<970,cta=frame>=1177;const special=hook||title||list||flip||cta;return <AbsoluteFill style={{background:'#000'}}><OffthreadVideo src={staticFile('integra02.mp4')}/>{!special&&<><CityTag/><div style={{position:'absolute',left:70,right:70,top:1650,height:230,display:'flex',alignItems:'center',justifyContent:'center'}}>{CUES.filter(c=>frame>=c.s&&frame<c.e).map(c=><Caption key={c.s} cue={c}/>)}</div></>}{hook&&<><CityTag/><Hook/></>}{title&&<PlanningTitle/>}{list&&<FactorList/>}{flip&&<StrategicFlip/>}{cta&&<FinalCTA/>}<Sequence from={59} durationInFrames={25}><Audio src={staticFile('sfx/transition-soft.mp3')} volume={.34}/></Sequence><Sequence from={248} durationInFrames={50}><Audio src={staticFile('sfx/transition-tech.mp3')} volume={.32}/></Sequence><Sequence from={332} durationInFrames={35}><Audio src={staticFile('sfx/transition-soft.mp3')} volume={.36}/></Sequence>{[352,400,443,497,531].map(x=><Sequence key={x} from={x} durationInFrames={22}><Audio src={staticFile('sfx/hitech-touch-magnet.mp3')} volume={.23}/></Sequence>)}<Sequence from={803} durationInFrames={38}><Audio src={staticFile('sfx/transition-tech.mp3')} volume={.32}/></Sequence>{[839,852].map(x=><Sequence key={x} from={x} durationInFrames={22}><Audio src={staticFile('sfx/pop-electric.mp3')} volume={.27}/></Sequence>)}<Sequence from={1177} durationInFrames={45}><Audio src={staticFile('sfx/impact-deep-whoosh.mp3')} volume={.34}/></Sequence><Sequence from={1301} durationInFrames={20}><Audio src={staticFile('sfx/ui-select-click.mp3')} volume={.46}/></Sequence></AbsoluteFill>};

const FactorListTimed=()=>{const frame=useCurrentFrame()-332;const items=[['FATURAMENTO',20],['FOLHA DE PAGAMENTO',68],['ATIVIDADE EXERCIDA',111],['CUSTOS',165],['PARTICULARIDADES',199]] as const;const phases=[[270,'COMPARAR CENÁRIOS'],[340,'IDENTIFICAR'],[371,'IDENTIFICAR OPORTUNIDADES'],[403,'ECONOMIA'],[431,'ECONOMIA DENTRO DA LEGISLAÇÃO']] as const;const current=[...phases].reverse().find(([start])=>frame>=start);const fp=current?interpolate(frame,[current[0],current[0]+6],[0,1],{extrapolateLeft:'clamp',extrapolateRight:'clamp',easing:Easing.out(Easing.cubic)}):0;return <AbsoluteFill style={{background:`linear-gradient(145deg,${CREAM},#dce9e5)`,fontFamily:'Arial',color:NAVY,alignItems:'center',justifyContent:'center'}}><div style={{position:'absolute',top:465,font:'900 51px Arial',letterSpacing:3,color:GREEN}}>O QUE É ANALISADO?</div><div style={{display:'flex',flexDirection:'column',gap:28,transform:`translateY(${interpolate(frame,[0,470],[18,-18])}px)`}}>{items.map(([s,start],i)=>{const p=interpolate(frame,[start,start+18],[0,1],{extrapolateLeft:'clamp',extrapolateRight:'clamp',easing:Easing.out(Easing.back(1.08))});return <div key={s} style={{width:1030,padding:'28px 40px',background:'rgba(255,255,255,.74)',borderLeft:`10px solid ${GREEN}`,fontSize:52,fontWeight:900,opacity:Math.min(1,p*2.2),transform:`scale(${.78+p*.22}) translateY(${(1-p)*14}px)`,boxShadow:'0 10px 24px rgba(7,29,45,.1)'}}>{String(i+1).padStart(2,'0')}  {s}</div>})}</div>{current&&<div key={current[1]} style={{position:'absolute',bottom:480,left:40,right:40,textAlign:'center',font:'900 43px Arial',color:GREEN,opacity:fp,filter:`blur(${(1-fp)*8}px)`,transform:`translateY(${(1-fp)*20}px)`}}>{current[1]}</div>}</AbsoluteFill>};

const FinalCTATimed=()=>{const frame=useCurrentFrame()-1177;const btnIn=interpolate(frame,[124,130],[0,1],{extrapolateLeft:'clamp',extrapolateRight:'clamp',easing:Easing.out(Easing.cubic)});const btn=interpolate(frame,[130,136,143],[1,1.12,1],{extrapolateLeft:'clamp',extrapolateRight:'clamp',easing:Easing.out(Easing.cubic)});const glow=interpolate(frame,[130,140],[0,1],{extrapolateLeft:'clamp',extrapolateRight:'clamp'});return <AbsoluteFill style={{background:`radial-gradient(circle at 50% 45%,#116052 0%,${NAVY} 58%,#04121c 100%)`,fontFamily:'Arial',color:'#fff',justifyContent:'center',alignItems:'center',textAlign:'center'}}><CtaStage start={0} end={34}>VOCÊ É<br/><span style={{color:MINT}}>EMPRESÁRIO?</span></CtaStage><CtaStage start={34} end={90}>QUER TOMAR<br/><span style={{color:MINT}}>DECISÕES TRIBUTÁRIAS?</span></CtaStage><CtaStage start={90} end={124}>COM<br/><span style={{color:MINT}}>ESTRATÉGIA?</span></CtaStage>{frame>=124&&<div style={{position:'absolute',top:1030,background:RED,color:'#fff',borderRadius:70,padding:'31px 110px',font:'900 72px Arial',opacity:btnIn,filter:`blur(${(1-btnIn)*8}px)`,transform:`scale(${btn})`,boxShadow:`0 0 ${25+glow*45}px rgba(189,36,55,${.35+glow*.35})`}}>ME SIGA</div>}<div style={{position:'absolute',bottom:520,font:'800 34px Arial',letterSpacing:6,color:'#9fc1cc'}}>CONTEÚDO TRIBUTÁRIO SEM COMPLICAÇÃO</div></AbsoluteFill>};

export const Integra02Fixed2:React.FC=()=>{const frame=useCurrentFrame();const hook=frame<248,title=frame>=248&&frame<332,list=frame>=332&&frame<803,flip=frame>=803&&frame<970,cta=frame>=1177;const special=hook||title||list||flip||cta;return <AbsoluteFill style={{background:'#000'}}><OffthreadVideo src={staticFile('integra02.mp4')}/>{!special&&<><CityTag/><div style={{position:'absolute',left:70,right:70,top:1650,height:230,display:'flex',alignItems:'center',justifyContent:'center'}}>{CUES.filter(c=>frame>=c.s&&frame<c.e).map(c=><Caption key={c.s} cue={c}/>)}</div></>}{hook&&<><CityTag/><Hook/></>}{title&&<PlanningTitle/>}{list&&<FactorListTimed/>}{flip&&<StrategicFlip/>}{cta&&<FinalCTATimed/>}<Sequence from={59} durationInFrames={25}><Audio src={staticFile('sfx/transition-soft.mp3')} volume={.34}/></Sequence><Sequence from={248} durationInFrames={50}><Audio src={staticFile('sfx/transition-tech.mp3')} volume={.32}/></Sequence><Sequence from={332} durationInFrames={35}><Audio src={staticFile('sfx/transition-soft.mp3')} volume={.36}/></Sequence>{[352,400,443,497,531].map(x=><Sequence key={x} from={x} durationInFrames={22}><Audio src={staticFile('sfx/hitech-touch-magnet.mp3')} volume={.23}/></Sequence>)}<Sequence from={803} durationInFrames={38}><Audio src={staticFile('sfx/transition-tech.mp3')} volume={.32}/></Sequence>{[839,852].map(x=><Sequence key={x} from={x} durationInFrames={22}><Audio src={staticFile('sfx/pop-electric.mp3')} volume={.27}/></Sequence>)}<Sequence from={1177} durationInFrames={45}><Audio src={staticFile('sfx/impact-deep-whoosh.mp3')} volume={.34}/></Sequence><Sequence from={1301} durationInFrames={20}><Audio src={staticFile('sfx/ui-select-click.mp3')} volume={.46}/></Sequence></AbsoluteFill>};

const HookRefined=()=> <div style={{position:'absolute',inset:0,fontFamily:'Arial'}}><TimedHookLine start={2} end={58}>MUITOS <span style={{color:MINT}}>EMPRESÁRIOS</span></TimedHookLine><TimedHookLine start={59} end={114}>PAGAM IMPOSTOS<br/><span style={{color:MINT}}>TODO MÊS</span></TimedHookLine><TimedHookLine start={118} end={166}>SEM SABER SE ESTÃO<br/><span style={{color:RED}}>REALMENTE...</span></TimedHookLine><TimedHookLine start={166} end={248}>NO REGIME TRIBUTÁRIO<br/><span style={{color:MINT}}>MAIS ADEQUADO</span></TimedHookLine></div>;

const CenterPhrase:React.FC<{start:number;end:number;children:React.ReactNode}>=({start,end,children})=>{const frame=useCurrentFrame()-332;const enter=interpolate(frame,[start,start+6],[0,1],{extrapolateLeft:'clamp',extrapolateRight:'clamp',easing:Easing.out(Easing.cubic)});const exit=interpolate(frame,[end-5,end],[1,0],{extrapolateLeft:'clamp',extrapolateRight:'clamp'});const p=Math.min(enter,exit);if(frame<start||frame>=end)return null;return <div style={{position:'absolute',top:1190,left:90,right:90,textAlign:'center',font:'900 78px Arial',lineHeight:1.04,letterSpacing:1,color:NAVY,opacity:p,filter:`blur(${(1-p)*10}px)`,transform:`translateY(${(1-p)*28}px) scale(${.94+p*.06})`,textShadow:'0 5px 18px rgba(7,29,45,.14)'}}>{children}</div>};

const FactorListDynamic=()=>{const frame=useCurrentFrame()-332;const items=[['FATURAMENTO',20],['FOLHA DE PAGAMENTO',68],['ATIVIDADE EXERCIDA',111],['CUSTOS',165],['PARTICULARIDADES',199]] as const;const compact=interpolate(frame,[260,278],[0,1],{extrapolateLeft:'clamp',extrapolateRight:'clamp',easing:Easing.inOut(Easing.cubic)});return <AbsoluteFill style={{background:`linear-gradient(145deg,${CREAM},#dce9e5)`,fontFamily:'Arial',color:NAVY,alignItems:'center',justifyContent:'center'}}><div style={{position:'absolute',top:465,transform:`translateY(${-compact*260}px) scale(${1-compact*.16})`,font:'900 51px Arial',letterSpacing:3,color:GREEN}}>O QUE É ANALISADO?</div><div style={{display:'flex',flexDirection:'column',gap:28,transform:`translateY(${interpolate(frame,[0,470],[18,-18])-compact*315}px) scale(${1-compact*.31})`,transformOrigin:'center center'}}>{items.map(([s,start],i)=>{const p=interpolate(frame,[start,start+18],[0,1],{extrapolateLeft:'clamp',extrapolateRight:'clamp',easing:Easing.out(Easing.back(1.08))});return <div key={s} style={{width:1030,padding:'28px 40px',background:'rgba(255,255,255,.82)',borderLeft:`10px solid ${GREEN}`,fontSize:52,fontWeight:900,opacity:Math.min(1,p*2.2),transform:`scale(${.78+p*.22}) translateY(${(1-p)*14}px)`,boxShadow:'0 10px 24px rgba(7,29,45,.1)'}}>{String(i+1).padStart(2,'0')}  {s}</div>})}</div><CenterPhrase start={270} end={310}>COMPARAR OS <span style={{color:GREEN}}>CENÁRIOS</span></CenterPhrase><CenterPhrase start={310} end={340}><span style={{color:GREEN}}>TRIBUTÁRIOS</span></CenterPhrase><CenterPhrase start={340} end={371}>IDENTIFICAR</CenterPhrase><CenterPhrase start={371} end={403}>AS <span style={{color:GREEN}}>OPORTUNIDADES</span></CenterPhrase><CenterPhrase start={403} end={431}>DE <span style={{color:GREEN}}>ECONOMIA</span></CenterPhrase><CenterPhrase start={431} end={471}>DENTRO DA <span style={{color:GREEN}}>LEGISLAÇÃO</span></CenterPhrase></AbsoluteFill>};

const FinalCTARefined=()=>{const frame=useCurrentFrame()-1177;const btnIn=interpolate(frame,[124,130],[0,1],{extrapolateLeft:'clamp',extrapolateRight:'clamp',easing:Easing.out(Easing.cubic)});const btn=interpolate(frame,[130,136,143],[1,1.12,1],{extrapolateLeft:'clamp',extrapolateRight:'clamp',easing:Easing.out(Easing.cubic)});const glow=interpolate(frame,[130,140],[0,1],{extrapolateLeft:'clamp',extrapolateRight:'clamp'});return <AbsoluteFill style={{background:`radial-gradient(circle at 50% 45%,#116052 0%,${NAVY} 58%,#04121c 100%)`,fontFamily:'Arial',color:'#fff',justifyContent:'center',alignItems:'center',textAlign:'center'}}><CtaStage start={0} end={34}>VOCÊ É<br/><span style={{color:MINT}}>EMPRESÁRIO?</span></CtaStage><CtaStage start={34} end={90}>QUER TOMAR<br/><span style={{color:MINT}}>DECISÕES TRIBUTÁRIAS?</span></CtaStage><CtaStage start={90} end={124}>COM<br/><span style={{color:MINT}}>ESTRATÉGIA</span></CtaStage>{frame>=124&&<div style={{position:'absolute',top:1030,background:RED,color:'#fff',borderRadius:70,padding:'31px 110px',font:'900 72px Arial',opacity:btnIn,filter:`blur(${(1-btnIn)*8}px)`,transform:`scale(${btn})`,boxShadow:`0 0 ${25+glow*45}px rgba(189,36,55,${.35+glow*.35})`}}>ME SIGA</div>}<div style={{position:'absolute',bottom:520,font:'800 34px Arial',letterSpacing:6,color:'#9fc1cc'}}>CONTEÚDO TRIBUTÁRIO SEM COMPLICAÇÃO</div></AbsoluteFill>};

export const Integra02Fixed3:React.FC=()=>{const frame=useCurrentFrame();const hook=frame<248,title=frame>=248&&frame<332,list=frame>=332&&frame<803,flip=frame>=803&&frame<970,cta=frame>=1177;const special=hook||title||list||flip||cta;return <AbsoluteFill style={{background:'#000'}}><OffthreadVideo src={staticFile('integra02.mp4')}/>{!special&&<><CityTag/><div style={{position:'absolute',left:70,right:70,top:1650,height:230,display:'flex',alignItems:'center',justifyContent:'center'}}>{CUES.filter(c=>frame>=c.s&&frame<c.e).map(c=><Caption key={c.s} cue={c}/>)}</div></>}{hook&&<><CityTag/><HookRefined/></>}{title&&<PlanningTitle/>}{list&&<FactorListDynamic/>}{flip&&<StrategicFlip/>}{cta&&<FinalCTARefined/>}<Sequence from={59} durationInFrames={25}><Audio src={staticFile('sfx/transition-soft.mp3')} volume={.34}/></Sequence><Sequence from={248} durationInFrames={50}><Audio src={staticFile('sfx/transition-tech.mp3')} volume={.32}/></Sequence><Sequence from={332} durationInFrames={35}><Audio src={staticFile('sfx/transition-soft.mp3')} volume={.36}/></Sequence>{[352,400,443,497,531].map(x=><Sequence key={x} from={x} durationInFrames={22}><Audio src={staticFile('sfx/hitech-touch-magnet.mp3')} volume={.23}/></Sequence>)}<Sequence from={803} durationInFrames={38}><Audio src={staticFile('sfx/transition-tech.mp3')} volume={.32}/></Sequence>{[839,852].map(x=><Sequence key={x} from={x} durationInFrames={22}><Audio src={staticFile('sfx/pop-electric.mp3')} volume={.27}/></Sequence>)}<Sequence from={1177} durationInFrames={45}><Audio src={staticFile('sfx/impact-deep-whoosh.mp3')} volume={.34}/></Sequence><Sequence from={1301} durationInFrames={20}><Audio src={staticFile('sfx/ui-select-click.mp3')} volume={.46}/></Sequence></AbsoluteFill>};
