import React from "react";
import {AbsoluteFill, Audio, Easing, Img, interpolate, OffthreadVideo, Sequence, spring, staticFile, useCurrentFrame, useVideoConfig} from "remotion";
import CircularText from "./vendor/react-bits/CircularText";
import StarBorder from "./vendor/react-bits/StarBorder";

const blue="#14529A", green="#21B35B", orange="#F47A18", ink="#071C2B", white="#FFFFFF", red="#E74536";
const clamp={extrapolateLeft:"clamp",extrapolateRight:"clamp"} as const;
const ease=Easing.bezier(.16,1,.3,1);
const reveal=(f:number,a:number,b:number)=>interpolate(f,[a,b],[0,1],{...clamp,easing:ease});

// Adaptado do BlurText do React Bits: blur e deslocamento agora são determinados pelo frame.
const BlurWords:React.FC<{text:string;color?:string;fontSize?:number;delay?:number}>=({text,color=white,fontSize=88,delay=4})=>{const f=useCurrentFrame();return <div style={{display:"flex",flexWrap:"wrap",justifyContent:"center",gap:"0 .24em",fontSize,fontWeight:950,lineHeight:.92,color,textAlign:"center"}}>{text.split(" ").map((word,i)=>{const p=reveal(f,i*delay,i*delay+12);return <span key={`${word}-${i}`} style={{display:"inline-block",opacity:p,filter:`blur(${(1-p)*18}px)`,transform:`translateY(${(1-p)*54}px) scale(${.84+.16*p})`}}>{word}</span>})}</div>};

// DecryptedText do React Bits adaptado para caracteres determinísticos por frame.
const DecryptText:React.FC<{text:string;start?:number;color?:string}>=({text,start=0,color=white})=>{const f=useCurrentFrame();const chars="0123456789#$%?+=ABCDEFGHIJKLMNOPQRSTUVWXYZ";return <span>{text.split("").map((char,i)=>{const done=f>=start+i*2;const code=chars[(i*7+Math.max(0,f-start)*3)%chars.length];return <span key={i} style={{color:done?color:green,opacity:done?1:.66}}>{char===" "?" ":done?char:code}</span>})}</span>};

// PixelTransition do React Bits convertido de hover/GSAP para mosaico sequencial por frame.
const PixelCurtain:React.FC<{color?:string}>=({color=ink})=>{const f=useCurrentFrame();return <AbsoluteFill style={{pointerEvents:"none",display:"grid",gridTemplateColumns:"repeat(10,1fr)",gridTemplateRows:"repeat(10,1fr)"}}>{Array.from({length:100},(_,i)=>{const order=(i*37)%100;const p=interpolate(f,[order*.09,order*.09+6],[1,0],clamp);return <div key={i} style={{background:color,opacity:p,transform:`scale(${p})`}}/>})}</AbsoluteFill>};

const GridBackground:React.FC<{light?:boolean}>=({light=false})=>{const f=useCurrentFrame();return <AbsoluteFill style={{background:light?"linear-gradient(145deg,#fff,#eef5f1)":"radial-gradient(circle at 50% 30%,#16486a,#071c2b 72%)",overflow:"hidden"}}><div style={{position:"absolute",inset:-200,opacity:light?.18:.12,backgroundImage:`linear-gradient(${light?blue:white} 2px,transparent 2px),linear-gradient(90deg,${light?blue:white} 2px,transparent 2px)`,backgroundSize:"74px 74px",transform:`perspective(900px) rotateX(58deg) translateY(${interpolate(f,[0,180],[80,-35])}px) scale(1.25)`}}/><div style={{position:"absolute",width:620,height:620,borderRadius:"50%",left:-220,top:-250,background:`radial-gradient(circle,${green}55,transparent 68%)`}}/><div style={{position:"absolute",width:700,height:700,borderRadius:"50%",right:-320,bottom:-360,background:`radial-gradient(circle,${orange}55,transparent 68%)`}}/></AbsoluteFill>};

const Source:React.FC=()=>{const f=useCurrentFrame();const zoom=interpolate(f,[0,155,156,320,321,560,561,760,761,999],[1.015,1.075,1.025,1.065,1.02,1.075,1.025,1.06,1.02,1.08],{...clamp,easing:Easing.inOut(Easing.quad)});const x=interpolate(f,[0,250,500,750,999],[0,-12,9,-8,6],clamp);return <OffthreadVideo src={staticFile("source.mp4")} style={{width:"100%",height:"100%",objectFit:"cover",transform:`translateX(${x}px) scale(${zoom})`}}/>};

const LocationHook:React.FC=()=>{const f=useCurrentFrame(),{fps}=useVideoConfig();const p=spring({frame:f,fps,config:{damping:15,stiffness:150,mass:.7}});return <AbsoluteFill style={{fontFamily:"Arial,sans-serif",pointerEvents:"none"}}><div style={{position:"absolute",left:58,top:340,width:610,opacity:p,transform:`translateX(${(1-p)*-80}px)`,textShadow:"0 5px 24px rgba(0,0,0,.55)"}}><StarBorder as="div" className="hook-star" color={green} speed="2.8s" thickness={3}>ATENÇÃO, EMPRESÁRIO</StarBorder><div style={{fontSize:58,fontWeight:950,color:white,lineHeight:.88,marginTop:22}}>SUA EMPRESA<br/><span style={{fontSize:47,color:orange}}>É DE PARAUAPEBAS?</span></div></div><div style={{position:"absolute",right:86,top:330,width:260,height:260,display:"grid",placeItems:"center",opacity:reveal(f,12,24),transform:`scale(${.72+.28*reveal(f,12,24)})`}}><div style={{position:"absolute",width:250,height:250,borderRadius:"50%",background:"rgba(7,28,43,.82)",boxShadow:`0 0 0 ${8+5*Math.sin(f*.18)}px rgba(33,179,91,.16),0 20px 55px rgba(0,0,0,.3)`}}/><div style={{position:"absolute",transform:`rotate(${f*1.8}deg) scale(1.18)`}}><CircularText text="PARAUAPEBAS • NEGÓCIO LOCAL • " spinDuration={6}/></div><div style={{position:"relative",fontSize:74,color:orange,fontWeight:950}}>01</div></div></AbsoluteFill>};

const StopScreen:React.FC=()=>{const f=useCurrentFrame();return <AbsoluteFill style={{fontFamily:"Arial,sans-serif",color:white}}><GridBackground/><div style={{position:"absolute",left:90,top:130,opacity:.7,transform:`rotate(${-f*1.2}deg) scale(1.5)`}}><CircularText text="PARE • ASSISTA • ENTENDA • " spinDuration={5}/></div><div style={{position:"absolute",inset:0,display:"flex",flexDirection:"column",alignItems:"center",justifyContent:"center"}}><StarBorder as="div" className="stop-star" color={orange} speed="2.2s" thickness={4}>PARE TUDO</StarBorder><div style={{marginTop:35,maxWidth:1220}}><BlurWords text="ESTE VÍDEO É PARA VOCÊ" color={white} fontSize={112} delay={3}/></div><div style={{marginTop:50,fontSize:25,fontWeight:850,letterSpacing:7,color:green,opacity:reveal(f,26,40)}}>30 SEGUNDOS PODEM MUDAR SUA DECISÃO</div></div><PixelCurtain color="#F2F7F4"/></AbsoluteFill>};

// Spotlight Card do React Bits convertido de posição do mouse para varredura por frame.
const RegimeCard:React.FC<{title:string;color:string;delay:number;selected?:boolean}>=({title,color,delay,selected})=>{const f=useCurrentFrame(),{fps}=useVideoConfig();const p=spring({frame:f-delay,fps,config:{damping:18,stiffness:135,mass:.75}});const light=interpolate(f,[delay,delay+40],[0,100],clamp);return <div style={{position:"relative",width:380,height:300,borderRadius:34,overflow:"hidden",background:"rgba(255,255,255,.08)",border:`3px solid ${selected?color:"rgba(255,255,255,.2)"}`,boxShadow:selected?`0 0 42px ${color}55`:"0 18px 50px rgba(0,0,0,.2)",opacity:p,transform:`translateY(${(1-p)*75}px) scale(${.82+.18*p})`}}><div style={{position:"absolute",width:280,height:280,borderRadius:"50%",left:`calc(${light}% - 140px)`,top:10,background:`radial-gradient(circle,${color}55,transparent 68%)`}}/><div style={{position:"relative",height:"100%",display:"flex",flexDirection:"column",alignItems:"center",justifyContent:"center",color:white,textAlign:"center"}}><div style={{fontSize:25,letterSpacing:3,fontWeight:850,opacity:.72}}>REGIME</div><div style={{fontSize:52,lineHeight:.94,fontWeight:950,marginTop:12}}>{title}</div>{selected&&<div style={{marginTop:26,borderRadius:999,padding:"10px 20px",background:color,color:ink,fontSize:22,fontWeight:950}}>ANALISAR</div>}</div></div>};

const RegimeChoice:React.FC=()=>{const f=useCurrentFrame();return <AbsoluteFill style={{fontFamily:"Arial,sans-serif",color:white}}><GridBackground/><div style={{position:"absolute",top:110,left:80,right:80,textAlign:"center"}}><div style={{fontSize:27,fontWeight:900,letterSpacing:7,color:green}}>NÃO ESCOLHA NO AUTOMÁTICO</div><BlurWords text="QUAL REGIME FAZ SENTIDO?" fontSize={83} delay={3}/></div><div style={{position:"absolute",left:80,right:80,top:410,display:"flex",justifyContent:"center",gap:28}}><RegimeCard title="MEI" color={orange} delay={12}/><RegimeCard title="SIMPLES NACIONAL" color={green} delay={20} selected/><RegimeCard title="OUTRO REGIME" color={blue} delay={28}/></div><div style={{position:"absolute",bottom:118,left:0,right:0,textAlign:"center",fontSize:30,fontWeight:850,color:"rgba(255,255,255,.72)",opacity:reveal(f,45,62)}}>O MAIS CONHECIDO NEM SEMPRE É O MAIS ECONÔMICO.</div></AbsoluteFill>};

// Toggle skeuomórfico inspirado no Galaxy/Uiverse, dirigido por frame.
const TaxLoss:React.FC=()=>{const f=useCurrentFrame();const on=reveal(f,18,35);return <AbsoluteFill style={{fontFamily:"Arial,sans-serif",pointerEvents:"none"}}><div style={{position:"absolute",left:55,top:340,width:560,padding:"28px 32px",borderRadius:30,background:"rgba(70,15,18,.92)",boxShadow:"0 22px 65px rgba(0,0,0,.34)",opacity:reveal(f,0,10),transform:`translateX(${interpolate(reveal(f,0,10),[0,1],[-70,0])}px)`}}><div style={{fontSize:25,fontWeight:900,letterSpacing:4,color:"#FFAAA3"}}>ANOS DEPOIS...</div><div style={{fontSize:60,fontWeight:950,lineHeight:.92,color:white,marginTop:8}}>PAGOU MAIS<br/><span style={{color:"#FF6D62"}}>SEM PRECISAR</span></div><div style={{display:"flex",alignItems:"center",gap:20,marginTop:24}}><div style={{width:150,height:64,borderRadius:99,padding:5,background:on>.5?green:red,boxShadow:"inset 0 0 18px rgba(0,0,0,.3)"}}><div style={{width:54,height:54,borderRadius:"50%",background:"linear-gradient(145deg,#fff,#bbb)",boxShadow:"4px 7px 14px rgba(0,0,0,.35)",transform:`translateX(${on*86}px)`}}/></div><div style={{fontSize:25,fontWeight:900,color:white}}>POTENCIAL A ANALISAR</div></div></div></AbsoluteFill>};

const Diagnostic:React.FC=()=>{const f=useCurrentFrame();return <AbsoluteFill style={{fontFamily:"Arial,sans-serif",color:white}}><GridBackground/><Img src={staticFile("logo-integra.svg")} style={{position:"absolute",left:62,top:55,width:320,height:120,objectFit:"contain",filter:"brightness(0) invert(1)"}}/><div style={{position:"absolute",left:70,right:70,top:230}}><div style={{fontSize:28,fontWeight:900,letterSpacing:7,color:green}}>ANÁLISE EM ANDAMENTO</div><div style={{fontSize:77,fontWeight:950,lineHeight:.94,marginTop:15}}><DecryptText text="DIAGNÓSTICO COMPLETO" start={4}/></div><div style={{display:"flex",gap:18,marginTop:58}}>{["DADOS","REGIMES","CENÁRIOS","OPORTUNIDADES"].map((x,i)=>{const p=reveal(f,28+i*17,40+i*17);return <div key={x} style={{flex:1,minHeight:210,borderRadius:28,border:`2px solid ${i===3?green:"rgba(255,255,255,.22)"}`,background:i===3?"rgba(33,179,91,.15)":"rgba(255,255,255,.06)",display:"flex",flexDirection:"column",alignItems:"center",justifyContent:"center",opacity:p,transform:`translateY(${(1-p)*55}px) rotateX(${(1-p)*18}deg)`}}><div style={{display:"flex",gap:9,marginBottom:24}}>{[0,1,2].map(n=><span key={n} style={{width:14,height:14,borderRadius:"50%",background:i===3?green:blue,transform:`scale(${.75+.35*Math.sin((f-n*5)*.18)})`,boxShadow:`0 0 0 ${4+3*Math.sin((f-n*5)*.18)}px rgba(33,179,91,.12)`}}/>)}</div><div style={{fontSize:23,fontWeight:900,letterSpacing:2}}>{x}</div></div>})}</div></div><PixelCurtain color="#F7FAF8"/></AbsoluteFill>};

const SimulationScreen:React.FC=()=>{const f=useCurrentFrame();const cursor=interpolate(f,[18,95],[0,2],{...clamp,easing:Easing.inOut(Easing.quad)});const idx=Math.min(2,Math.floor(cursor+.01));return <AbsoluteFill style={{fontFamily:"Arial,sans-serif",color:ink}}><GridBackground light/><Img src={staticFile("logo-integra.svg")} style={{position:"absolute",left:62,top:55,width:360,height:130,objectFit:"contain"}}/><div style={{position:"absolute",top:210,left:70,right:70}}><div style={{fontSize:29,fontWeight:900,letterSpacing:5,color:blue}}>SIMULAÇÃO TRIBUTÁRIA</div><div style={{fontSize:72,fontWeight:950,lineHeight:.92}}>COMPARE ANTES<br/>DE DECIDIR.</div></div><div style={{position:"absolute",left:70,right:70,top:475,display:"flex",gap:22}}>{["SIMPLES","PRESUMIDO","REAL"].map((name,i)=>{const active=i===idx;return <div key={name} style={{flex:1,height:280,borderRadius:30,padding:26,background:active?ink:white,border:`3px solid ${active?green:"#D8E2E7"}`,boxShadow:active?`0 20px 55px ${blue}44`:"0 14px 34px rgba(0,0,0,.08)",transform:`translateY(${active?-18:0}px)`}}><div style={{fontSize:23,fontWeight:900,letterSpacing:2,color:active?green:blue}}>{name}</div><div style={{marginTop:34,fontSize:45,fontWeight:950,color:active?white:ink}}>COMPARAR</div><div style={{height:12,borderRadius:99,marginTop:34,background:"#DDE7EA",overflow:"hidden"}}><div style={{height:"100%",width:active?"100%":"35%",background:active?green:orange}}/></div></div>})}</div><div style={{position:"absolute",bottom:100,left:70,right:70,textAlign:"center",fontSize:34,fontWeight:900,color:blue,opacity:reveal(f,66,82)}}>MOSTRAMOS ONDE PODE EXISTIR ECONOMIA LEGAL.</div></AbsoluteFill>};

// Text shimmer e botão inspirados nos componentes do 21st.dev, com progresso por frame.
const FinalCTA:React.FC=()=>{const f=useCurrentFrame(),{fps}=useVideoConfig();const p=spring({frame:f-8,fps,config:{damping:16,stiffness:145,mass:.72}});const shine=interpolate(f,[20,105],[-80,120],clamp);const press=interpolate(f,[68,75,81],[1,.9,1],clamp);return <AbsoluteFill style={{fontFamily:"Arial,sans-serif",color:white}}><GridBackground/><Img src={staticFile("logo-integra.svg")} style={{position:"absolute",left:540,top:90,width:360,height:135,objectFit:"contain",filter:"brightness(0) invert(1)"}}/><div style={{position:"absolute",inset:"285px 100px 210px",display:"flex",flexDirection:"column",alignItems:"center",textAlign:"center"}}><div style={{fontSize:26,fontWeight:900,letterSpacing:8,color:green,opacity:reveal(f,4,16)}}>SEU PRÓXIMO PASSO</div><div style={{fontSize:94,fontWeight:950,lineHeight:.88,marginTop:22,opacity:p,transform:`translateY(${(1-p)*55}px)`}}><DecryptText text="SOLICITE AGORA" start={12}/><br/>SEU DIAGNÓSTICO</div><div style={{position:"relative",marginTop:72,padding:5,borderRadius:999,overflow:"hidden",transform:`scale(${press})`}}><div style={{position:"absolute",width:520,height:170,left:`${shine}%`,top:-45,background:`radial-gradient(circle,${orange},transparent 62%)`,filter:"blur(8px)"}}/><div style={{position:"relative",padding:"25px 54px",borderRadius:999,background:ink,border:`3px solid ${orange}`,fontSize:34,fontWeight:950,boxShadow:`0 18px 48px rgba(0,0,0,.34),inset 0 0 30px ${orange}22`}}>CLIQUE NO BOTÃO ABAIXO <span style={{color:orange}}>→</span></div></div></div><PixelCurtain/></AbsoluteFill>};

const Sfx:React.FC<{from:number;file:string;volume:number}>=({from,file,volume})=><Sequence from={from}><Audio src={staticFile(file)} volume={()=>Math.min(1,volume*2)}/></Sequence>;

export const IntegraVideo01Edit:React.FC=()=> <AbsoluteFill style={{background:ink}}><Source/><AbsoluteFill style={{background:"linear-gradient(180deg,rgba(3,17,26,.12),transparent 42%,rgba(3,17,26,.12))",pointerEvents:"none"}}/><Sequence from={5} durationInFrames={150}><LocationHook/></Sequence><Sequence from={157} durationInFrames={60}><StopScreen/></Sequence><Sequence from={218} durationInFrames={215}><RegimeChoice/></Sequence><Sequence from={433} durationInFrames={128}><TaxLoss/></Sequence><Sequence from={562} durationInFrames={125}><Diagnostic/></Sequence><Sequence from={687} durationInFrames={175}><SimulationScreen/></Sequence><Sequence from={862} durationInFrames={137}><FinalCTA/></Sequence>
  <Sfx from={5} file="whoosh.wav" volume={.10}/><Sfx from={17} file="ding.wav" volume={.08}/>
  <Sfx from={157} file="whip.wav" volume={.13}/><Sfx from={165} file="tone-rise.wav" volume={.07}/><Sfx from={190} file="ding.wav" volume={.06}/>
  <Sfx from={218} file="page-turn.wav" volume={.10}/><Sfx from={230} file="whoosh.wav" volume={.06}/><Sfx from={238} file="whoosh.wav" volume={.07}/><Sfx from={246} file="whoosh.wav" volume={.06}/><Sfx from={253} file="switch.wav" volume={.09}/>
  <Sfx from={433} file="tone-rise.wav" volume={.10}/><Sfx from={451} file="switch.wav" volume={.11}/>
  <Sfx from={562} file="scanner.wav" volume={.11}/><Sfx from={590} file="ding.wav" volume={.055}/><Sfx from={607} file="ding.wav" volume={.06}/><Sfx from={624} file="ding.wav" volume={.065}/><Sfx from={641} file="ding.wav" volume={.075}/>
  <Sfx from={687} file="page-turn.wav" volume={.11}/><Sfx from={705} file="whoosh.wav" volume={.07}/><Sfx from={744} file="switch.wav" volume={.08}/><Sfx from={782} file="switch.wav" volume={.08}/><Sfx from={829} file="ding.wav" volume={.07}/>
  <Sfx from={862} file="whoosh.wav" volume={.13}/><Sfx from={878} file="tone-rise.wav" volume={.08}/><Sfx from={930} file="mouse-click.wav" volume={.18}/>
 </AbsoluteFill>;
