'use strict';
const crypto=require('node:crypto');
const fail=(status,message)=>Object.assign(new Error(message),{status});
const id=value=>{if(!/^\d+$/.test(String(value||'')))throw fail(400,'Identificador inválido.');return String(value)};
const text=(value,max=200)=>{if(typeof value!=='string'||!value.trim()||value.length>max)throw fail(400,'Preencha os textos dentro do limite indicado.');return value.trim()};
const link=value=>{try{const u=new URL(value);if(u.protocol==='https:'&&!u.username&&!u.password)return u.href}catch{}throw fail(400,'Informe um endereço HTTPS válido.')};
async function body(req){let size=0,chunks=[];for await(const chunk of req){size+=chunk.length;if(size>29*1024*1024)throw fail(413,'Arquivo acima do limite de 20 MB.');chunks.push(chunk)}try{return JSON.parse(Buffer.concat(chunks).toString())}catch{throw fail(400,'Dados inválidos.')}}

function createCampaignManager({graph,rows,authorizeAccounts,connection,read,write,fetchImpl,planCampaign=require("./campaign-planner").plan}){
  const locks=new Set(), planning=new Set();
  const current=(user,conn)=>{if(connection(user).revision!==conn.revision)throw fail(409,'A conexão mudou. Reabra esta conta antes de continuar.')};
  async function access(user,account,manage=false){const {conn,accounts}=await authorizeAccounts(user,[account]);if(manage&&!conn.scopes?.includes('ads_management'))throw fail(403,'Autorize o gerenciamento de anúncios. O app precisa ter ads_management aprovado para seu acesso.');return {conn,account:accounts.find(a=>a.id===account)}}
  async function owned(conn,account,object,fields='id,account_id,name,status,effective_status'){const item=await graph(conn.token,id(object),{fields});if('act_'+item.account_id!==account)throw fail(403,'Este item não pertence à conta selecionada.');return item}
  async function pages(conn,account){return rows(conn.token,account+'/promote_pages',{fields:'id,name'})}
  async function pageAccess(conn,account,page){if(!(await pages(conn,account)).some(p=>p.id===id(page)))throw fail(403,'Esta Página não está disponível para anunciar nesta conta.')}
  async function locationFor(conn,query){const result=await graph(conn.token,'search',{type:'adgeolocation',location_types:JSON.stringify(['city','region','country']),q:query,limit:10});const item=(result.data||[]).find(x=>['city','region','country'].includes(x.type)&&x.key&&/^[A-Z]{2}$/.test(x.country_code||x.key));if(!item)throw fail(400,'A Meta não encontrou a localização sugerida. Descreva a cidade, estado ou país com mais precisão.');return {key:String(item.key),type:item.type,name:item.name,country:item.country_code||item.key,region:item.region||''}}
  async function interestsFor(conn,queries){const found=[];for(const query of queries){try{const result=await graph(conn.token,'search',{type:'adinterest',q:query,limit:5});const item=(result.data||[]).find(x=>x.id&&x.name);if(item&&!found.some(x=>x.id===String(item.id)))found.push({id:String(item.id),name:String(item.name).slice(0,120)})}catch{}}return found}
  async function post(user,conn,endpoint,params){current(user,conn);let response,payload;try{const data=params instanceof FormData?params:new URLSearchParams(Object.entries(params).map(([k,v])=>[k,typeof v==='object'?JSON.stringify(v):String(v)]));response=await fetchImpl(new URL('https://graph.facebook.com/v25.0/'+endpoint),{method:'POST',headers:{Authorization:'Bearer '+conn.token},body:data,signal:AbortSignal.timeout(120000)});payload=await response.json()}catch{throw fail(502,'A Meta não confirmou a operação. Atualize a lista antes de tentar criar novamente.')}if(!response.ok||payload.error){const e=payload.error||{};throw fail(e.code===190?409:400,(e.error_user_msg||e.error_user_title||'A Meta recusou a operação. Confira o acesso, as configurações e as regras da conta.').slice(0,600))}current(user,conn);return payload}
  async function handle(req,user,url){const action=url.pathname.slice('/api/ads-manager/'.length),account=url.searchParams.get('account');const {conn,account:accountInfo}=await access(user,account,req.method!=='GET');
    if(req.method==='GET'){
      if(action==='locations'){
        const q=String(url.searchParams.get('q')||'').trim();if(q.length<2||q.length>100)throw fail(400,'Digite uma localização com 2 a 100 caracteres.');
        const data=await graph(conn.token,'search',{type:'adgeolocation',location_types:JSON.stringify(['city','region','country']),q,limit:20});current(user,conn);
        const items=(data.data||[]).filter(x=>['city','region','country'].includes(x.type)&&x.key&&/^[A-Z]{2}$/.test(x.country_code||x.key)).map(x=>({key:String(x.key),type:x.type,name:x.name,country:x.country_code||x.key,region:x.region||''}));
        const saved=read('ads-locations',user.id)||[];write('ads-locations',user.id,[...saved.filter(x=>!items.some(y=>x.key===y.key&&x.type===y.type)),...items].slice(-200));return {items};
      }
      if(action==='campaigns') {const items=await rows(conn.token,account+'/campaigns',{fields:'id,name,objective,status,effective_status,daily_budget,lifetime_budget'});current(user,conn);return {items,currency:accountInfo.currency||'',canManage:conn.scopes?.includes('ads_management')||false}}
      if(action==='adsets'){await owned(conn,account,url.searchParams.get('campaign'));return {items:await rows(conn.token,id(url.searchParams.get('campaign'))+'/adsets',{fields:'id,name,account_id,campaign_id,status,effective_status,daily_budget,destination_type,optimization_goal,promoted_object'})}}
      if(action==='ads'){await owned(conn,account,url.searchParams.get('adset'));return {items:await rows(conn.token,id(url.searchParams.get('adset'))+'/ads',{fields:'id,name,status,effective_status,creative{thumbnail_url}'})}}
      if(action==='assets'){const p=await pages(conn,account);let instagram=[],warning='';try{instagram=await rows(conn.token,account+'/instagram_accounts',{fields:'id,username,profile_pic'})}catch{warning='Não foi possível consultar os perfis do Instagram. Verifique a autorização.'}return {pages:p,instagram,warning}}
      if(action==='forms'){const page=url.searchParams.get('page');await pageAccess(conn,account,page);return {items:await rows(conn.token,id(page)+'/leadgen_forms',{fields:'id,name,status'})}}
      if(action==='operations')return {items:(read('ads-operations',user.id)||[]).filter(x=>x.account===account).map(({key,account,state,created,error,updated})=>({key,account,state,created,error,updated}))};
      throw fail(404,'Consulta não encontrada.');
    }
    if(req.method!=='POST')throw fail(405,'Método não permitido.');
    const p=await body(req);
    if(action==='plan'){
      if(planning.has(user.id))throw fail(409,'Já existe uma campanha sendo preparada. Aguarde.');
      const last=read('ads-plan-time',user.id);if(last&&Date.now()-last<15000)throw fail(429,'Aguarde alguns segundos antes de gerar novamente.');
      if(typeof p.description!=='string'||p.description.trim().length<12||p.description.length>1500)throw fail(400,'Descreva a campanha em 12 a 1500 caracteres.');
      const available=await pages(conn,account);if(!available.length)throw fail(403,'Esta conta não possui uma Página disponível para anunciar.');
      const page=available.find(x=>x.id===p.page)||available[0];
      planning.add(user.id);try{
        let examples=[],sourceMedia=null,destinationValues={},sourceAds=[];try{const data=await graph(conn.token,account+'/ads',{fields:'name,creative{body,title,image_hash,thumbnail_url,object_story_spec}',limit:10});sourceAds=data.data||[];for(const ad of sourceAds){const story=ad.creative?.object_story_spec;if(story?.page_id!==page.id)continue;const linkData=story.link_data,cta=linkData?.call_to_action?.value;if(p.destination==='form'&&cta?.lead_gen_form_id)destinationValues={form:String(cta.lead_gen_form_id)};if(p.destination==='site'&&linkData?.link){try{const u=new URL(linkData.link);if(u.protocol==='https:'&&!u.username&&!u.password&&!['wa.me','www.facebook.com','facebook.com'].includes(u.hostname))destinationValues={url:u.href}}catch{}}if(p.destination==='whatsapp'&&linkData?.link){try{const u=new URL(linkData.link);if(u.hostname==='wa.me'&&/^\d{10,15}$/.test(u.pathname.slice(1)))destinationValues={phone:u.pathname.slice(1)}}catch{}}if(Object.keys(destinationValues).length)break}const source=(data.data||[]).find(x=>x.creative?.object_story_spec?.page_id===page.id&&(x.creative.image_hash||x.creative.object_story_spec.link_data?.image_hash));if(source){const value=source.creative.image_hash||source.creative.object_story_spec.link_data.image_hash;let preview='';try{const u=new URL(source.creative.thumbnail_url);if(u.protocol==='https:'&&!u.username&&!u.password&&!u.searchParams.has('access_token'))preview=u.href}catch{}if(preview)sourceMedia={key:crypto.randomUUID(),account,kind:'image',value,created:Date.now(),preview}}examples=(data.data||[]).filter(x=>x.creative?.object_story_spec?.page_id===page.id).slice(0,5).map(x=>({name:String(x.name||'').slice(0,200),title:String(x.creative.title||x.creative.object_story_spec.link_data?.name||'').slice(0,100),text:String(x.creative.body||x.creative.object_story_spec.link_data?.message||'').slice(0,2200)}))}catch{}
        write('ads-plan-time',user.id,Date.now());
        const draft=await planCampaign({page:page.name,pages:available.map(x=>x.name),currency:accountInfo.currency,description:p.description,examples});for(const ad of sourceAds){const linkData=ad.creative?.object_story_spec?.link_data,cta=linkData?.call_to_action?.value;if(draft.destination==='form'&&cta?.lead_gen_form_id){destinationValues={form:String(cta.lead_gen_form_id)};break}if(draft.destination==='site'&&linkData?.link){try{const u=new URL(linkData.link);if(u.protocol==='https:'&&!u.username&&!u.password&&!['wa.me','www.facebook.com','facebook.com'].includes(u.hostname)){destinationValues={url:u.href};break}}catch{}}if(draft.destination==='whatsapp'&&linkData?.link){try{const u=new URL(linkData.link);if(u.hostname==='wa.me'&&/^\d{10,15}$/.test(u.pathname.slice(1))){destinationValues={phone:u.pathname.slice(1)};break}}catch{}}}const location=await locationFor(conn,draft.locationQuery),interests=await interestsFor(conn,draft.interestQueries);current(user,conn);
        const saved=read('ads-locations',user.id)||[];write('ads-locations',user.id,[...saved.filter(x=>x.key!==location.key||x.type!==location.type),location].slice(-200));if(sourceMedia)write('ads-media',user.id,[...(read('ads-media',user.id)||[]).slice(-199),sourceMedia]);return {draft:{...draft,...destinationValues,...(sourceMedia?{media:sourceMedia.key,mediaPreview:sourceMedia.preview}:{}),page:page.id,countries:[location.country],location,interests},reviewRequired:true};
      }finally{planning.delete(user.id)}
    }
    if(action==='upload'){
      if(!['image/jpeg','image/png','video/mp4'].includes(p.type)||typeof p.data!=='string'||!/^[A-Za-z0-9+/]+={0,2}$/.test(p.data))throw fail(400,'Envie uma imagem JPG/PNG ou um vídeo MP4.');
      const bytes=Buffer.from(p.data,'base64');if(!bytes.length||bytes.length>20*1024*1024)throw fail(413,'Use um arquivo de até 20 MB.');
      const image=p.type.startsWith('image/');const valid=p.type==='image/png'?bytes.subarray(0,8).equals(Buffer.from('89504e470d0a1a0a','hex')):p.type==='image/jpeg'?bytes[0]===255&&bytes[1]===216:bytes.toString('ascii',4,8)==='ftyp';if(!valid)throw fail(400,'O conteúdo não corresponde ao formato do arquivo.');
      let result;if(image)result=await post(user,conn,account+'/adimages',{bytes:p.data});else{const form=new FormData();form.append('source',new Blob([bytes],{type:p.type}),'creative.mp4');result=await post(user,conn,account+'/advideos',form)}
      const value=image?Object.values(result.images||{})[0]?.hash:result.id;if(!value)throw fail(502,'A Meta não retornou o identificador do criativo.');const media={key:crypto.randomUUID(),account,kind:image?'image':'video',value,created:Date.now()};write('ads-media',user.id,[...(read('ads-media',user.id)||[]).slice(-199),media]);return {key:media.key,kind:media.kind};
    }
    if(action==='status'){
      if(!['campaign','adset','ad'].includes(p.kind)||!['ACTIVE','PAUSED'].includes(p.status)||p.confirm!==true)throw fail(400,'Confirme a alteração de status.');
      // Verify the object is present on the exact typed edge, not merely an arbitrary Graph node.
      const edge={campaign:'campaigns',adset:'adsets',ad:'ads'}[p.kind];const items=await rows(conn.token,account+'/'+edge,{fields:'id,name,status'});if(!items.some(x=>x.id===id(p.id)))throw fail(403,'Item não autorizado nesta conta.');
      const result=await post(user,conn,id(p.id),{status:p.status});if(result.success!==true)throw fail(502,'A Meta não confirmou a alteração.');const updated=await owned(conn,account,p.id);return {item:updated};
    }
    if(action!=='create')throw fail(404,'Operação não encontrada.');
    if(!/^[a-f0-9-]{36}$/.test(p.key||'')||p.confirm!==true)throw fail(400,'Revise e confirme o anúncio antes de enviar.');
    const opKey=user.id+':'+p.key,previous=(read('ads-operations',user.id)||[]).find(x=>x.key===p.key);
    if(previous){if(previous.account!==account)throw fail(403,'Operação de outra conta.');if(previous.state==='complete')return previous;throw fail(409,'Esta tentativa já foi registrada. Consulte as operações e os itens criados antes de iniciar outro anúncio.');}
    if(locks.has(opKey))throw fail(409,'Criação em andamento.');locks.add(opKey);
    let operation;
    const save=()=>{operation.updated=Date.now();const items=read('ads-operations',user.id)||[];write('ads-operations',user.id,[...items.filter(x=>x.key!==p.key),operation].slice(-500))};
    try{
      const name=text(p.name),headline=text(p.headline,100),message=text(p.message,2200),destination=p.destination;
      if(!['site','whatsapp','form'].includes(destination))throw fail(400,'Escolha o destino do anúncio.');
      const page=id(p.page);await pageAccess(conn,account,page);
      let instagram;if(p.instagram){instagram=id(p.instagram);if(!(await rows(conn.token,account+'/instagram_accounts',{fields:'id'})).some(x=>x.id===instagram))throw fail(403,'Instagram não autorizado nesta conta.')}
      const media=(read('ads-media',user.id)||[]).find(x=>x.key===p.media&&x.account===account);if(!media)throw fail(400,'Envie o criativo nesta conta.');
      let target,cta,form;if(destination==='site'){target=link(p.url);cta={type:'LEARN_MORE',value:{link:target}}}
      if(destination==='whatsapp'){if(!/^\d{10,15}$/.test(p.phone||''))throw fail(400,'Informe o WhatsApp com código do país e DDD.');target='https://wa.me/'+p.phone;cta={type:'WHATSAPP_MESSAGE',value:{link:target}}}
      if(destination==='form'){form=id(p.form);if(!(await rows(conn.token,page+'/leadgen_forms',{fields:'id,status'})).some(x=>x.id===form&&x.status==='ACTIVE'))throw fail(400,'Selecione um formulário ativo desta Página.');target='https://www.facebook.com/'+page;cta={type:'SIGN_UP',value:{lead_gen_form_id:form}}}
      let existing;if(p.adset){existing=await owned(conn,account,p.adset,'id,account_id,campaign_id,destination_type,promoted_object');const expected={site:'WEBSITE',whatsapp:'WHATSAPP',form:'ON_AD'}[destination];if(existing.destination_type!==expected)throw fail(400,'O conjunto selecionado usa outro destino.');if(existing.promoted_object?.page_id&&existing.promoted_object.page_id!==page)throw fail(400,'O conjunto utiliza outra Página.');}
      let budget,targeting,categories;if(!existing){if(!['BRL','USD','EUR','GBP'].includes(accountInfo.currency))throw fail(400,'Criação de conjuntos disponível para contas em BRL, USD, EUR e GBP.');budget=Number(p.dailyBudget);if(!Number.isFinite(budget)||budget<=0||budget>100000)throw fail(400,'Informe um orçamento diário válido, até 100.000 na moeda da conta.');const category=p.category||'';if(!['','HOUSING','EMPLOYMENT','FINANCIAL_PRODUCTS_SERVICES','ISSUES_ELECTIONS_POLITICS'].includes(category))throw fail(400,'Categoria especial inválida.');categories=category?[category]:[];const countries=Array.isArray(p.countries)?p.countries:[];if(!countries.length||countries.length>10||countries.some(x=>!/^[A-Z]{2}$/.test(x)))throw fail(400,'Informe os países do público com códigos de duas letras.');const min=Number(p.ageMin),max=Number(p.ageMax);if(!Number.isInteger(min)||!Number.isInteger(max)||min<18||max>65||min>max)throw fail(400,'Confira a faixa etária.');const interests=Array.isArray(p.interests)?p.interests:[];if(interests.length>5||interests.some(x=>!x||!/^\d+$/.test(String(x.id||''))||typeof x.name!=='string'||x.name.length>120))throw fail(400,'Os interesses precisam ser confirmados pela Meta. Gere o plano novamente.');const automatic=p.placements==='automatic';if(!automatic&&p.placements!=='feeds'&&p.placements!==undefined)throw fail(400,'Posicionamento inválido.');targeting={geo_locations:{countries},age_min:categories.length?18:min,age_max:categories.length?65:max,...(interests.length?{flexible_spec:[{interests:interests.map(x=>({id:String(x.id),name:x.name}))}]}:{}),...(automatic?{}:{publisher_platforms:instagram?['facebook','instagram']:['facebook'],facebook_positions:['feed'],...(instagram?{instagram_positions:['stream']}:{})})};}
      if(p.location&&!existing){const geo=(read('ads-locations',user.id)||[]).find(x=>x.key===p.location.key&&x.type===p.location.type);if(!geo)throw fail(400,'A localização não está mais disponível. Busque novamente.');if(p.countries.length!==1||p.countries[0]!==geo.country)throw fail(400,'Confira o país da localização.');targeting.geo_locations=geo.type==='country'?{countries:[geo.country]}:geo.type==='region'?{regions:[{key:geo.key}]}:{cities:[{key:geo.key}]};}
      let videoImage;if(media.kind==='video'){const info=await graph(conn.token,media.value,{fields:'status'});if(['error','failed'].includes(info.status?.video_status))throw fail(400,'A Meta não conseguiu processar este vídeo. Envie outro MP4 ou exporte o arquivo novamente.');if(info.status?.video_status!=='ready')throw fail(409,'O vídeo ainda está sendo processado pela Meta. Aguarde e tente novamente.');const thumbs=await rows(conn.token,media.value+'/thumbnails',{fields:'uri'});videoImage=thumbs[0]?.uri;if(!videoImage)throw fail(409,'A capa do vídeo ainda não está disponível. Aguarde.');}
      operation={key:p.key,account,state:'creating',created:{},updated:Date.now()};save();
      const create=async(kind,endpoint,data)=>{operation.stage=kind;save();const result=await post(user,conn,endpoint,data);if(!result.id)throw fail(502,'A Meta não retornou o ID de '+kind);operation.created[kind]=result.id;save();return result.id};
      let campaign=existing?.campaign_id,adset=existing?.id;
      if(!existing){campaign=await create('campaign',account+'/campaigns',{name,objective:{site:'OUTCOME_TRAFFIC',whatsapp:'OUTCOME_ENGAGEMENT',form:'OUTCOME_LEADS'}[destination],special_ad_categories:categories,...(categories.length?{special_ad_category_country:p.countries}:{}),status:'PAUSED',is_adset_budget_sharing_enabled:false});adset=await create('adset',account+'/adsets',{name:name+' — Público',campaign_id:campaign,daily_budget:Math.round(budget*100),billing_event:'IMPRESSIONS',optimization_goal:{site:'LINK_CLICKS',whatsapp:'CONVERSATIONS',form:'LEAD_GENERATION'}[destination],destination_type:{site:'WEBSITE',whatsapp:'WHATSAPP',form:'ON_AD'}[destination],bid_strategy:'LOWEST_COST_WITHOUT_CAP',targeting,...(destination!=='site'?{promoted_object:{page_id:page,...(destination==='whatsapp'?{whatsapp_phone_number:p.phone}:{})}}:{}),status:'PAUSED'})}
      const story={page_id:page,...(instagram?{instagram_user_id:instagram}:{})};if(media.kind==='image')story.link_data={image_hash:media.value,link:target,message,name:headline,call_to_action:cta};else story.video_data={video_id:media.value,image_url:videoImage,message,title:headline,call_to_action:cta};
      const creative=await create('creative',account+'/adcreatives',{name,object_story_spec:story});await create('ad',account+'/ads',{name,adset_id:adset,creative:{creative_id:creative},status:'PAUSED'});operation.state='complete';operation.campaign=campaign;operation.adset=adset;save();return operation;
    }catch(e){if(operation){operation.state='needs_review';operation.error=e.message;save();throw fail(e.status||502,e.message+' Os itens já criados ficaram pausados. Consulte Operações antes de repetir.')}throw e}finally{locks.delete(opKey)}
  }
  return {handle};
}
module.exports={createCampaignManager};
