(() => {
  const $ = id => document.getElementById(id), status = text => { $('flowStatus').textContent = text; };
  const api = async (path, options = {}) => { const response = await fetch(path, {headers: {'Content-Type': 'application/json', 'X-Require-Personal-Meta': '1', ...(options.headers || {})}, ...options}), body = await response.json().catch(() => ({})); if (!response.ok) throw new Error(body.error || 'Não foi possível concluir esta ação.'); return body; };
  const setOptions = (element, rows, placeholder, selected = '') => { element.innerHTML = `<option value="">${placeholder}</option>` + rows.map(row => `<option value="${row.id}" ${String(row.id) === String(selected) ? 'selected' : ''}>${row.name}</option>`).join(''); };
  async function loadForms(selected = '') { if (!$('flowPage').value) return setOptions($('flowForm'), [], 'Escolha um formulário'); setOptions($('flowForm'), [], 'Carregando formulários…'); const data = await api(`/api/flow/meta/forms?pageId=${encodeURIComponent($('flowPage').value)}`); setOptions($('flowForm'), data.forms || [], 'Escolha um formulário', selected); }
  async function loadGroups(selected = '') { const instance = $('flowInstance').value.trim(); if (!instance) return setOptions($('flowGroup'), [], 'Informe a instância WhatsApp'); setOptions($('flowGroup'), [], 'Carregando grupos…'); const data = await api(`/api/flow/whatsapp/groups?instance=${encodeURIComponent(instance)}`); setOptions($('flowGroup'), data.groups || [], 'Escolha um grupo', selected); }
  async function connect() { status('Carregando a sua conexão Facebook…'); try { const [catalog, flow] = await Promise.all([api('/api/flow/meta/catalog'), api('/api/flow/config')]); setOptions($('flowAdAccount'), catalog.accounts || [], 'Escolha uma conta', flow.facebook?.adAccountId); setOptions($('flowPage'), catalog.pages || [], 'Escolha uma página', flow.facebook?.pageId); $('flowInstance').value = flow.whatsapp?.instance || ''; $('flowEnabled').checked = Boolean(flow.enabled); if (flow.facebook?.pageId) await loadForms(flow.facebook.formId); if (flow.whatsapp?.instance) await loadGroups(flow.whatsapp.groupJid); status('Facebook conectado. Escolha o formulário e o grupo para ativar o fluxo.'); } catch (error) { status(error.message); } }
  let qrTimer = null;
  async function showQr(payload) { if (!payload.qr) throw new Error('A Evolution não retornou um QR Code.'); $('flowInstance').value = payload.instance; $('flowQrImage').src = payload.qr; $('flowQrPanel').hidden = false; $('flowQrStatus').textContent = 'Leia o QR Code em WhatsApp > Aparelhos conectados.'; clearInterval(qrTimer); qrTimer = setInterval(async () => { try { const state = await api(`/api/flow/whatsapp/status?instance=${encodeURIComponent(payload.instance)}`); if (state.connected) { clearInterval(qrTimer); $('flowQrStatus').textContent = 'WhatsApp conectado. Carregando grupos…'; await loadGroups(); $('flowQrPanel').hidden = true; status('WhatsApp conectado. Escolha o grupo de destino.'); } } catch (error) { $('flowQrStatus').textContent = error.message; } }, 2500); }
  $('flowConnectWhatsApp').onclick = async event => { event.currentTarget.disabled = true; status('Gerando QR Code do WhatsApp…'); try { await showQr(await api('/api/flow/whatsapp/instance', {method: 'POST', body: '{}'})); status('Leia o QR Code para conectar seu WhatsApp.'); } catch (error) { status(error.message); } finally { event.currentTarget.disabled = false; } };
  $('flowConnect').onclick = connect;
  $('flowPage').onchange = () => loadForms();
  $('flowToggleConnection').onclick = event => { const connected = event.currentTarget.getAttribute('aria-pressed') !== 'true'; event.currentTarget.setAttribute('aria-pressed', connected); event.currentTarget.textContent = connected ? 'Blocos conectados' : 'Conectar blocos'; document.querySelector('.flow-canvas').classList.toggle('connected', connected); };
  $('flowBuilder').onsubmit = async event => { event.preventDefault(); status('Ativando fluxo…'); const flow = {enabled: $('flowEnabled').checked, facebook: {adAccountId: $('flowAdAccount').value, pageId: $('flowPage').value, formId: $('flowForm').value}, whatsapp: {instance: $('flowInstance').value.trim(), groupJid: $('flowGroup').value}}; try { await api('/api/flow/config', {method: 'PUT', body: JSON.stringify(flow)}); status(flow.enabled ? 'Fluxo ativo. A Página foi inscrita automaticamente nos novos leads.' : 'Fluxo salvo como inativo.'); } catch (error) { status(error.message); } };
})();
