const escape=value=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
export async function initializeLocalTools({showView,identity}){
 const local=!!window.HURTZ_LOCAL;
 const $=s=>document.querySelector(s),main=$('main');
 const request=async(url,options={})=>{const response=await fetch(url,options),data=await response.json();if(!response.ok)throw new Error(data.error||'A operação local falhou.');return data};
 const json=(method,payload)=>({method,headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});
 const banner=document.createElement('div');banner.className='local-environment';banner.textContent=local?'LOCALHOST · '+(identity?.user?.email||'Entre no espaço local')+' · Dados salvos neste computador':'Seu espaço · '+(identity?.user?.email||'');main.prepend(banner);
 const typography=document.createElement('style');typography.textContent='.local-tool-view{font:400 14px/1.55 "DM Sans",system-ui,sans-serif;color:#29231d}.local-tool-view h2,.local-tool-view h3{font-family:Manrope,system-ui,sans-serif}.local-tool-view h2{font-size:25px;margin:8px 0}.local-tool-view h3{font-size:18px}.local-tool-view button{font-family:inherit}.local-tool-view>p{color:#766d65;margin-bottom:22px}';document.head.append(typography);
 const styles=document.createElement('style');styles.textContent=`.local-environment{padding:12px 16px;border:1px solid #e9c69d;border-radius:9px;background:#fff2df;color:#563415;margin-bottom:18px;font-size:13px}.local-tool-view{padding:12px 0}.local-tool-view[hidden]{display:none}.local-tool-grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(290px,1fr));gap:18px}.local-tool-card{background:white;border:1px solid #e2dcd4;border-radius:14px;padding:22px}.local-tool-card h3{margin-top:0}.local-tool-card label{display:block;margin:14px 0}.local-tool-card input:not([type=checkbox]),.local-tool-card textarea{display:block;width:100%;box-sizing:border-box;border:1px solid #d9d0c5;border-radius:7px;padding:10px;margin-top:6px;font:inherit}.local-tool-card button,.local-tool-button{padding:10px 14px;border-radius:8px;border:1px solid #d7b394;background:#fff3e7;color:#773300;cursor:pointer;margin:4px 4px 4px 0}.local-tool-card button:disabled{opacity:.5}.local-tool-status{font-size:14px;white-space:pre-wrap;overflow-wrap:anywhere}.local-library-grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(270px,1fr));gap:16px;margin-top:18px}.local-library-grid article{background:#fff;border:1px solid #ddd;border-radius:10px;padding:18px;overflow-wrap:anywhere}.local-library-grid a{color:#923b00}.local-tool-card small{color:#6a625a;display:block;line-height:1.5}.local-tool-card button:focus-visible{outline:3px solid #007c91;outline-offset:3px}`;document.head.append(styles);
 const settings=document.createElement('section');settings.id='localSettings';settings.className='local-tool-view';settings.hidden=true;
 settings.innerHTML=`<h2>Configurações locais</h2><p>Conexões e preferências do seu usuário. As credenciais ficam protegidas no servidor deste computador.</p><div class="local-tool-grid"><article class="local-tool-card"><h3>Pesquisa de criativos</h3><form id="localApifyForm"><label>Token da Apify<input id="localApifyToken" type="password" autocomplete="new-password" placeholder="Cole para configurar ou substituir"></label><label><input id="localVisualAudit" type="checkbox"> Ativar análise visual pelo agente local</label><small>A pesquisa usa a Apify no servidor e não depende de um computador conectado.</small><button>Salvar pesquisa</button></form><p id="localApifyStatus" class="local-tool-status" role="status"></p></article><article class="local-tool-card"><h3>WhatsApp / Evolution</h3><form id="localEvolutionForm"><label>URL da Evolution<input id="localEvolutionUrl" type="url" placeholder="http://localhost:8080"></label><label>Chave de API<input id="localEvolutionKey" type="password" autocomplete="new-password" placeholder="Cole para configurar ou substituir"></label><button>Salvar Evolution</button></form><small>Depois, crie uma instância própria em Alertas. Instâncias de outros usuários não são exibidas.</small><p id="localEvolutionStatus" class="local-tool-status" role="status"></p></article><article class="local-tool-card"><h3>Facebook individual</h3><p>O login pelo Facebook depende de o aplicativo Meta aceitar o endereço local. Também é possível conectar um token de usuário do Tryv CRM.</p><form id="localMetaForm"><label>Token do seu usuário Facebook<input id="localMetaToken" type="password" autocomplete="new-password" required></label><button>Validar e conectar</button></form><p id="localMetaStatus" class="local-tool-status" role="status"></p></article><article class="local-tool-card"><h3>Ferramentas auxiliares</h3><p>Gere uma conexão restrita, válida por 7 dias.</p><button id="localExtensionConnection">Conexão da extensão TikTok</button><button id="localAgentConnection">Conexão do analisador</button><label id="localAccessLabel" hidden>Conexão gerada — copie para a ferramenta<textarea id="localAccessOutput" readonly rows="6"></textarea></label><small>Instale a extensão pela pasta Hurtz TikTok Collector. O analisador está em Hurtz Creative Analyzer. Essas ferramentas apontarão para localhost.</small></article><article class="local-tool-card"><h3>Verificação das integrações</h3><button id="localDiagnostics">Verificar conexões</button><p id="localDiagnosticsStatus" class="local-tool-status" role="status">A verificação não envia mensagens nem modera comentários.</p></article><article class="local-tool-card"><h3>Conta local</h3><p id="localIdentity"></p><p>Para testar outra pessoa, saia e crie uma conta no formulário de cadastro local.</p><button id="localAccountLogout">Sair desta conta</button><button id="localOwnerLogin">Abrir espaço de desenvolvimento</button></article></div>`;main.append(settings);
 const library=document.createElement('section');library.id='localLibrary';library.className='local-tool-view';library.hidden=true;library.innerHTML=`<h2>Biblioteca de criativos</h2><p>Referências salvas apenas no seu espaço. Os arquivos de vídeo não são armazenados aqui.</p><div class="local-tool-card"><form id="localLibraryForm"><label>Link público do vídeo<input id="localVideoUrl" type="url" placeholder="https://www.tiktok.com/@perfil/video/..." required></label><label>Título<input id="localVideoTitle" maxlength="500"></label><button>Salvar referência</button><button id="localLibraryRefresh" type="button">Atualizar biblioteca</button></form><p id="localLibraryStatus" role="status"></p></div><div id="localLibraryItems" class="local-library-grid"></div>`;main.append(library);
 const nav=$('.sidebar nav');let settingsNav=[...nav.querySelectorAll('a')].find(a=>a.textContent.includes('Configurações'));if(!settingsNav){settingsNav=document.createElement('a');nav.append(settingsNav)}settingsNav.id='settingsNav';settingsNav.href='?view=settings';if(!settingsNav.querySelector('svg'))settingsNav.innerHTML='<span class="nav-icon"><svg viewBox="0 0 24 24"><circle cx="12" cy="12" r="3"/><path d="M12 2v4m0 12v4M2 12h4m12 0h4M5 5l3 3m8 8 3 3M5 19l3-3m8-8 3-3"/></svg></span><span class="nav-label">Configurações</span>';
 const libraryNav=document.createElement('a');libraryNav.id='creativeLibraryNav';libraryNav.href='?view=library';libraryNav.innerHTML='<span class="nav-icon"><svg viewBox="0 0 24 24"><path d="M4 3v18M8 3v18M12 3v18M16 4l4 16"/></svg></span><span class="nav-label">Biblioteca</span>';nav.insertBefore(libraryNav,settingsNav);const separator=document.createElement('div');separator.className='sidebar-divider';separator.setAttribute('aria-hidden','true');nav.insertBefore(separator,settingsNav);const syncNav=()=>nav.querySelectorAll('a').forEach(a=>{const label=a.querySelector('.nav-label')?.textContent||a.textContent;a.setAttribute('aria-label',label);a.title=label;if(a.classList.contains('active'))a.setAttribute('aria-current','page');else a.removeAttribute('aria-current')});syncNav();new MutationObserver(syncNav).observe(nav,{subtree:true,attributes:true,attributeFilter:['class']});
 function display(view){settings.hidden=view!=='settings';library.hidden=view!=='library';if(['settings','library'].includes(view)){showView('overview');document.querySelectorAll('main>header,#summaryCards,#accounts,#analysis,#reports,#tasks,#alerts,#creativeSearch,#comments').forEach(el=>el.hidden=true);settings.hidden=view!=='settings';library.hidden=view!=='library';nav.querySelectorAll('a').forEach(a=>a.classList.toggle('active',a===(view==='settings'?settingsNav:libraryNav)));if(view==='settings')loadSettings();else loadLibrary()}else showView(view)}
 for(const[link,view]of [[settingsNav,'settings'],[libraryNav,'library']])link.onclick=e=>{e.preventDefault();history.replaceState(null,'','?view='+view);display(view)};
 const updateCreativeStatus=c=>{const badge=$('.creative-extension-status');if(badge){badge.textContent=c.apifyConfigured?'Apify configurada':'Configure a Apify';badge.classList.toggle('connected',c.apifyConfigured)}};
 async function loadSettings(){try{const c=await request('/api/local/settings');$('#localEvolutionUrl').value=c.evolutionUrl;$('#localVisualAudit').checked=c.visualAudit;$('#localVisualAudit').disabled=true;$('#localVisualAudit').closest('label').hidden=true;$('#localAgentConnection').hidden=true;if(c.sharedAnalyzer){$('#localVisualAudit').closest('label').title=c.analyzerOnline?'Análise visual compartilhada disponível para todos os usuários.':'Analisador compartilhado offline.';$('#localAgentConnection').hidden=true;}$('#localApifyStatus').textContent=c.apifyConfigured?'Credencial configurada.':'Credencial ainda não configurada.';$('#localEvolutionStatus').textContent=c.evolutionConfigured?'Evolution configurada.':'Configure URL e chave.';$('#localIdentity').textContent=c.user.email;updateCreativeStatus(c)}catch(e){$('#localDiagnosticsStatus').textContent=e.message}}
 function form(id,status,run){$(id).onsubmit=async e=>{e.preventDefault();const button=e.submitter;button.disabled=true;$(status).textContent='Salvando...';try{await run();$(status).textContent=local?'Configuração salva neste computador.':'Configuração salva no seu espaço.'}catch(error){$(status).textContent=error.message}finally{button.disabled=false}}}
 form('#localApifyForm','#localApifyStatus',async()=>{const token=$('#localApifyToken').value,p={visualAudit:$('#localVisualAudit').checked};if(token)p.apifyToken=token;const c=await request('/api/local/settings',json('PUT',p));$('#localApifyToken').value='';updateCreativeStatus(c)});
 form('#localEvolutionForm','#localEvolutionStatus',async()=>{const p={evolutionUrl:$('#localEvolutionUrl').value},key=$('#localEvolutionKey').value;if(key)p.evolutionKey=key;await request('/api/local/settings',json('PUT',p));$('#localEvolutionKey').value=''});
 form('#localMetaForm','#localMetaStatus',async()=>{const {nonce}=await request('/api/meta/challenge',{method:'POST'});await request('/api/meta/connection',json('POST',{nonce,accessToken:$('#localMetaToken').value.trim()}));$('#localMetaToken').value='';location.reload()});
 for(const[id,scope]of [['#localExtensionConnection','extension'],['#localAgentConnection','agent']])$(id).onclick=async()=>{try{const c=await request('/api/local/access',json('POST',{scope}));$('#localAccessLabel').hidden=false;$('#localAccessOutput').value=JSON.stringify(scope==='agent'?{api_url:c.api_url,token:c.token,ollama_url:'http://127.0.0.1:11434',model:'qwen2.5vl:3b'}:{api_url:c.api_url,token:c.token},null,2);$('#localAccessOutput').focus();$('#localAccessOutput').select()}catch(e){$('#localDiagnosticsStatus').textContent=e.message}};
 $('#localDiagnostics').onclick=async e=>{e.currentTarget.disabled=true;try{const result=await request('/api/local/diagnostics',{method:'POST'});$('#localDiagnosticsStatus').textContent=result.checks.map(c=>(c.ok?'✓ ':'• ')+c.name+': '+(c.detail||'OK')).join('\n')}catch(e){$('#localDiagnosticsStatus').textContent=e.message}finally{$('#localDiagnostics').disabled=false}};
 $('#localAccountLogout').onclick=()=>$('#logoutPersonalAnalytics').click();$('#localOwnerLogin').onclick=async()=>{const r=await request('/api/local/session',{method:'POST',headers:{'X-Local-Client':'1'}});localStorage.setItem('hurtz-monitor-session-v2',r.token);localStorage.removeItem('hurtz-local-signed-out');location.reload()};
 async function loadLibrary(){try{const {videos}=await request('/api/creative-videos');$('#localLibraryItems').innerHTML=videos.length?videos.map(v=>`<article><h3>${escape(v.title||'Vídeo salvo')}</h3><p>${escape(v.creator_name||v.platform||'')}</p><a href="${escape(v.video_url)}" target="_blank" rel="noopener noreferrer">Abrir vídeo original</a><p>${escape(v.notes||'')}</p><button class="local-tool-button" data-edit="${escape(v.id)}">Editar título</button><button class="local-tool-button" data-delete="${escape(v.id)}">Remover referência</button></article>`).join(''):'<p>Nenhuma referência salva. Adicione um link ou use a extensão.</p>';$('#localLibraryStatus').textContent=videos.length+' referência(s) no seu espaço.';$('#localLibraryItems').querySelectorAll('[data-delete]').forEach(b=>b.onclick=async()=>{try{await request('/api/creative-videos?id='+b.dataset.delete,{method:'DELETE'});loadLibrary()}catch(e){$('#localLibraryStatus').textContent=e.message}});$('#localLibraryItems').querySelectorAll('[data-edit]').forEach(b=>b.onclick=async()=>{const title=prompt('Título da referência',videos.find(v=>v.id===b.dataset.edit)?.title||'');if(title===null)return;try{await request('/api/creative-videos',json('PUT',{id:b.dataset.edit,title}));loadLibrary()}catch(e){$('#localLibraryStatus').textContent=e.message}})}catch(e){$('#localLibraryStatus').textContent=e.message}}
 form('#localLibraryForm','#localLibraryStatus',async()=>{await request('/api/creative-videos',json('POST',{videos:[{video_url:$('#localVideoUrl').value,title:$('#localVideoTitle').value}]}));$('#localLibraryForm').reset();await loadLibrary()});$('#localLibraryRefresh').onclick=loadLibrary;
 const commentsPermission=document.createElement('button');commentsPermission.type='button';commentsPermission.textContent='Autorizar leitura e moderação de comentários';$('#localMetaForm').after(commentsPermission);commentsPermission.onclick=()=>window.dispatchEvent(new Event('hurtz-connect-comments'));
 const runAlerts=document.createElement('button');runAlerts.id='localRunAlerts';runAlerts.type='button';runAlerts.textContent='Verificar alertas agora';$('.alert-actions')?.append(runAlerts);runAlerts.onclick=async()=>{runAlerts.disabled=true;try{const r=await request('/api/alerts/run',{method:'POST'});$('#alertFormStatus').textContent=r.message||`Verificação concluída: ${r.emitted||0} evento(s).`}catch(e){$('#alertFormStatus').textContent=e.message}finally{runAlerts.disabled=false}};
 if(identity)void loadSettings();else $('#localIdentity').textContent='Entre ou crie uma conta local.';
 $('.sidebar-foot strong').textContent=local?'Servidor local':'Monitoramento individual';$('.sidebar-foot small').textContent='Alertas a cada 15 min, se ativados';
 if(!local){$('#localOwnerLogin').hidden=true;const card=$('#localIdentity').closest('article');card.querySelector('h3').textContent='Sua conta';card.querySelectorAll('p')[1].textContent='Seu acesso usa o login do Traffic pocket. As integrações e os dados são separados por usuário.';settings.querySelectorAll('h2,h3,p,small').forEach(el=>{if(!el.children.length)el.textContent=el.textContent.replaceAll('neste computador','no seu espaço').replaceAll('de desenvolvimento','').replaceAll('localmente','no seu espaço').replaceAll('Configurações locais','Configurações')})}
 return display;
}
