const { app, BrowserWindow, WebContentsView, ipcMain, dialog } = require("electron");
const { spawn, execFileSync } = require("child_process");
const fs = require("fs");
const path = require("path");

const root = path.resolve(__dirname, "..");
const electron = path.join(root, "overlay", "node_modules", "electron", "dist", "electron.exe");
const tools = {
  meeting: { label: "Assistente de Reunião", url: null, path: path.join(root, "overlay", "index.html"), preload: path.join(root, "overlay", "preload.js") },
  whatsapp: { label: "Atendente WhatsApp", url: "http://127.0.0.1:3338", version: "1.4.0", project: path.join(root, "assistente-whatsapp"), entry: "src/index.js", preload: path.join(root, "assistente-whatsapp", "desktop", "preload.js") },
  leads: { label: "Extrator de Leads", url: "http://127.0.0.1:3340", version: "1.2.2", project: path.join(root, "extrator-leads"), entry: "src/server.js" },
};
let window; let active = "overview"; let detachedMeeting; let meetingBackend; let tunnel;
const views = new Map(); const processes = new Map(); const attachedViews = new Set();

function readEnv(project) {
  const file = path.join(project, ".env"); if (!fs.existsSync(file)) return {};
  return Object.fromEntries(fs.readFileSync(file, "utf8").split(/\r?\n/).filter((line) => line && !line.startsWith("#") && line.includes("=")).map((line) => { const at=line.indexOf("="); return [line.slice(0,at).trim(),line.slice(at+1).trim()]; }));
}
async function health(tool) { try { const response=await fetch(`${tool.url}/health`,{signal:AbortSignal.timeout(900)}); return response.ok?response.json():null; } catch { return null; } }
function stopPort(port, marker) { try { const command=`$c=Get-NetTCPConnection -LocalPort ${port} -State Listen -ErrorAction SilentlyContinue|Select-Object -First 1;if($c){$p=Get-CimInstance Win32_Process -Filter \"ProcessId=$($c.OwningProcess)\";if($p.CommandLine -match '${marker}'){Stop-Process -Id $p.ProcessId -Force}}`; execFileSync("powershell.exe",["-NoProfile","-Command",command],{windowsHide:true,stdio:"ignore"}); } catch {} }
async function ensureNodeService(name) {
  const tool=tools[name]; const current=await health(tool); if(current?.version===tool.version){if(name==="whatsapp")startTunnel();return true}
  if(current) { stopPort(name==="whatsapp"?3338:3340,name==="whatsapp"?"assistente-whatsapp":"extrator-leads"); await new Promise(r=>setTimeout(r,500)); }
  const child=spawn(electron,[path.join(tool.project,tool.entry)],{cwd:tool.project,windowsHide:true,stdio:"ignore",env:{...process.env,...readEnv(tool.project),ELECTRON_RUN_AS_NODE:"1"}}); processes.set(name,child);
  for(let i=0;i<60;i++){if((await health(tool))?.version===tool.version){if(name==="whatsapp")startTunnel();return true}await new Promise(r=>setTimeout(r,200));} return false;
}
function saveWebhook(url){const project=tools.whatsapp.project;const file=path.join(project,".env");let content=fs.existsSync(file)?fs.readFileSync(file,"utf8"):"";const line=`PUBLIC_WEBHOOK_URL=${url}`;content=/^PUBLIC_WEBHOOK_URL=.*$/m.test(content)?content.replace(/^PUBLIC_WEBHOOK_URL=.*$/m,line):`${content.trimEnd()}\n${line}\n`;fs.writeFileSync(file,content,"utf8")}
function cloudflaredPath(){try{return execFileSync("where.exe",["cloudflared.exe"],{windowsHide:true,encoding:"utf8"}).split(/\r?\n/).find(Boolean)}catch{const candidates=[path.join(process.env.ProgramFiles||"","cloudflared","cloudflared.exe"),path.join(process.env["ProgramFiles(x86)"]||"","cloudflared","cloudflared.exe"),path.join(process.env.LOCALAPPDATA||"","Microsoft","WinGet","Links","cloudflared.exe")];return candidates.find(candidate=>candidate&&fs.existsSync(candidate))}}
async function localWhatsAppApi(route,options={}){const token=readEnv(tools.whatsapp.project).HURTZ_ADMIN_TOKEN||"";return fetch(`${tools.whatsapp.url}${route}`,{...options,headers:{"content-type":"application/json",...(token?{authorization:`Bearer ${token}`}:{}) ,...(options.headers||{})}})}
async function configurePublicWebhook(baseUrl){const webhook=`${baseUrl.replace(/\/+$/,"")}/webhooks/evolution`;saveWebhook(webhook);const runtime=await localWhatsAppApi("/api/runtime/webhook",{method:"PUT",body:JSON.stringify({url:webhook})});if(!runtime.ok)throw new Error("Não foi possível registrar a URL pública no backend");const status=await localWhatsAppApi("/api/status").then(response=>response.json());for(const instance of status.instances||[])await localWhatsAppApi(`/api/instances/${encodeURIComponent(instance.name)}/webhook`,{method:"POST"})}
function startTunnel(){if(tunnel&&!tunnel.killed)return;const executable=cloudflaredPath();if(!executable)return;tunnel=spawn(executable,["tunnel","--url",tools.whatsapp.url,"--no-autoupdate"],{cwd:tools.whatsapp.project,windowsHide:true,stdio:["ignore","pipe","pipe"]});let configured=false;const inspect=data=>{if(configured)return;const match=String(data).match(/https:\/\/[a-z0-9-]+\.trycloudflare\.com/i);if(!match)return;configured=true;configurePublicWebhook(match[0]).catch(()=>{})};tunnel.stdout.on("data",inspect);tunnel.stderr.on("data",inspect)}
async function ensureOllama(){try{const r=await fetch("http://127.0.0.1:11434/api/tags",{signal:AbortSignal.timeout(1200)});if(r.ok)return true}catch{}const executable=path.join(process.env.LOCALAPPDATA||"","Programs","Ollama","ollama.exe");if(fs.existsSync(executable))spawn(executable,["serve"],{windowsHide:true,stdio:"ignore",detached:true});for(let i=0;i<25;i++){await new Promise(r=>setTimeout(r,300));try{if((await fetch("http://127.0.0.1:11434/api/tags",{signal:AbortSignal.timeout(600)})).ok)return true}catch{}}return false}
async function ensureMeeting(){if(meetingBackend&&!meetingBackend.killed)return true;const python=path.join(root,"venv","Scripts","python.exe");if(!fs.existsSync(python))return false;await ensureOllama();stopPort(8765,"backend.main.py");stopPort(8766,"backend.main.py");meetingBackend=spawn(python,["-u","backend/main.py"],{cwd:root,windowsHide:true,stdio:"ignore"});await new Promise(r=>setTimeout(r,1200));return !meetingBackend.killed}
function createToolView(name){if(views.has(name))return views.get(name);const tool=tools[name];const view=new WebContentsView({webPreferences:{preload:tool.preload,contextIsolation:true,nodeIntegration:false,sandbox:!tool.preload}});view.setBackgroundColor("#080a0b");views.set(name,view);return view}
function contentBounds(){const [width,height]=window.getContentSize();return{x:238,y:68,width:Math.max(1,width-238),height:Math.max(1,height-68)}}
function resize(){for(const [name,view] of views)if(!(name==="meeting"&&detachedMeeting)&&view.webContents&&!view.webContents.isDestroyed())view.setBounds(contentBounds())}
function hideAll(){for(const [name,view] of views)if(!(name==="meeting"&&detachedMeeting))view.setVisible(false)}
function sendStatus(extra={}){if(window&&!window.isDestroyed())window.webContents.send("os:status-changed",{active,meeting:Boolean(meetingBackend&&!meetingBackend.killed),whatsapp:Boolean(processes.get("whatsapp")&&!processes.get("whatsapp").killed),leads:Boolean(processes.get("leads")&&!processes.get("leads").killed),...extra})}
async function openTool(name){if(!["overview","meeting","whatsapp","leads"].includes(name))return{ok:false,error:"Ferramenta inválida"};active=name;hideAll();if(name==="overview"){sendStatus();return{ok:true}};if(name==="meeting"&&detachedMeeting){detachedMeeting.show();detachedMeeting.focus();sendStatus();return{ok:true}}sendStatus({loading:name});let ready=name==="meeting"?await ensureMeeting():await ensureNodeService(name);if(!ready){sendStatus({error:`Não foi possível iniciar ${tools[name].label}.`});return{ok:false}};const view=createToolView(name);if(!attachedViews.has(view)){window.contentView.addChildView(view);attachedViews.add(view)}view.setBounds(contentBounds());view.setVisible(true);if(!view.webContents.getURL()){if(name==="meeting")await view.webContents.loadFile(tools.meeting.path);else await view.webContents.loadURL(tools[name].url)}sendStatus();return{ok:true}}
function createWindow(){window=new BrowserWindow({width:1540,height:940,minWidth:980,minHeight:680,show:false,frame:false,backgroundColor:"#080a0b",title:"Hurtz OS",icon:path.join(root,"assets","hurtz-logo.ico"),webPreferences:{preload:path.join(__dirname,"preload.js"),contextIsolation:true,nodeIntegration:false,sandbox:true}});window.loadFile(path.join(__dirname,"shell","index.html"));window.on("resize",resize);window.once("ready-to-show",()=>window.show())}
function meetingParent(sender){return detachedMeeting&&detachedMeeting.webContents.id===sender.id?detachedMeeting:window}
ipcMain.handle("os:open",(_event,name)=>openTool(name));ipcMain.handle("os:status",()=>({active}));
ipcMain.handle("os:detach-meeting",async()=>{await openTool("meeting");const view=views.get("meeting");if(!view)return{ok:false};if(detachedMeeting){detachedMeeting.show();detachedMeeting.focus();return{ok:true}}view.setVisible(false);window.contentView.removeChildView(view);attachedViews.delete(view);detachedMeeting=new BrowserWindow({width:540,height:680,x:32,y:32,frame:false,transparent:true,alwaysOnTop:true,skipTaskbar:true,resizable:true,backgroundColor:"#00000000"});detachedMeeting.contentView.addChildView(view);view.setBounds({x:0,y:0,width:540,height:680});view.setVisible(true);detachedMeeting.on("resize",()=>{const [w,h]=detachedMeeting.getContentSize();view.setBounds({x:0,y:0,width:w,height:h})});detachedMeeting.on("closed",()=>{detachedMeeting=null;if(window&&!window.isDestroyed()){window.contentView.addChildView(view);attachedViews.add(view);view.setBounds(contentBounds());view.setVisible(active==="meeting")}});return{ok:true}});
ipcMain.on("overlay:minimize",event=>meetingParent(event.sender).minimize());ipcMain.on("overlay:close",()=>{if(detachedMeeting)detachedMeeting.close();else openTool("overview")});ipcMain.on("overlay:compact",(_event,compact)=>{if(detachedMeeting)detachedMeeting.setSize(540,compact?58:680,true)});ipcMain.handle("training:choose-pdfs",async event=>{const result=await dialog.showOpenDialog(meetingParent(event.sender),{title:"Selecionar documentos de treinamento",properties:["openFile","multiSelections"],filters:[{name:"Documentos PDF",extensions:["pdf"]}]});return result.canceled?[]:result.filePaths});
ipcMain.handle("security:admin-token",()=>readEnv(tools.whatsapp.project).HURTZ_ADMIN_TOKEN||"");
ipcMain.on("os:window",(_event,action)=>{if(!window)return;if(action==="minimize")window.minimize();if(action==="maximize")window.isMaximized()?window.unmaximize():window.maximize();if(action==="close")window.close()});
if(!app.requestSingleInstanceLock())app.quit();else{app.on("second-instance",()=>{if(window){window.show();window.focus()}});app.whenReady().then(createWindow);app.on("window-all-closed",()=>app.quit());app.on("before-quit",()=>{for(const child of processes.values())if(child&&!child.killed)child.kill();if(meetingBackend&&!meetingBackend.killed)meetingBackend.kill();if(tunnel&&!tunnel.killed)tunnel.kill()})}
