import React from 'react';
import {AbsoluteFill,Audio,Easing,interpolate,Sequence,staticFile,useCurrentFrame,Video} from 'remotion';
import {FlashCut} from './FlashCut';

const O='#ff7917',W='#fffaf3',D='#08090b';
const clamp={extrapolateLeft:'clamp',extrapolateRight:'clamp'} as const;
type Token={s:number;e:number;text:string;accent?:boolean;emphasis?:'rgb'|'cta'};
const T:Token[]=[
 {s:1,e:23,text:'SUA EMPRESA'},{s:23,e:57,text:'EM PARAUAPEBAS',accent:true},{s:57,e:68,text:'PODE ESTAR'},{s:68,e:88,text:'PAGANDO IMPOSTO'},
 {s:88,e:100,text:'A MAIS',accent:true,emphasis:'rgb'},{s:100,e:120,text:'SEM SABER',emphasis:'rgb'},
 {s:120,e:138,text:'MUITA GENTE'},{s:138,e:151,text:'FICA HÁ'},{s:151,e:162,text:'ANOS NO'},{s:162,e:186,text:'REGIME ERRADO',accent:true},
 {s:186,e:197,text:'AQUI NA'},{s:197,e:235,text:'INTEGRA CONTÁBIL',accent:true},{s:235,e:245,text:'FAZEMOS O'},{s:245,e:267,text:'DIAGNÓSTICO'},
 {s:267,e:291,text:'E MOSTRAMOS'},{s:291,e:309,text:'COM NÚMEROS',accent:true},{s:309,e:326,text:'QUANTO VOCÊ'},{s:326,e:354,text:'PODE ECONOMIZAR',accent:true},
 {s:354,e:367,text:'CLIQUE NO'},{s:367,e:380,text:'BOTÃO E',accent:true},{s:380,e:395,text:'PEÇA SEU'},{s:395,e:435,text:'DIAGNÓSTICO GRATUITO',accent:true,emphasis:'cta'},{s:435,e:450,text:'AGORA',accent:true},
];

const Grade:React.FC=()=> <AbsoluteFill style={{background:'linear-gradient(180deg,rgba(3,4,6,.18),rgba(3,4,6,.38) 48%,rgba(3,4,6,.94) 82%)',boxShadow:'inset 0 0 190px rgba(0,0,0,.55)'}}/>;
const Broll:React.FC<{src:string;start?:number;zoom?:number}>=({src,start=0,zoom=1.08})=>{const f=useCurrentFrame();const z=zoom+f*.0007;return <AbsoluteFill style={{overflow:'hidden',background:D}}><Video muted src={staticFile(src)} startFrom={start} style={{width:'100%',height:'100%',objectFit:'cover',transform:`scale(${z})`,filter:'saturate(.58) contrast(1.14) brightness(.72) sepia(.08)'}}/><AbsoluteFill style={{background:'linear-gradient(115deg,rgba(255,121,23,.2),transparent 43%)',mixBlendMode:'screen'}}/><Grade/></AbsoluteFill>};

const RiskHUD:React.FC=()=>{const f=useCurrentFrame();const p=interpolate(f,[8,25],[0,1],clamp);return <div style={{position:'absolute',top:155,left:70,right:70,height:10,borderRadius:9,background:'rgba(255,255,255,.18)',overflow:'hidden'}}><div style={{height:'100%',width:`${p*82}%`,background:O,boxShadow:`0 0 24px ${O}`}}/></div>};
const RegimeCard:React.FC=()=>{const f=useCurrentFrame();const p=interpolate(f,[5,15],[0,1],{...clamp,easing:Easing.out(Easing.back(1.7))});const out=interpolate(f,[66,76],[1,0],clamp);return <div style={{position:'absolute',top:160,left:82,right:82,display:'flex',gap:18,alignItems:'center',padding:'24px 28px',border:'2px solid rgba(255,121,23,.8)',borderRadius:24,background:'rgba(8,9,11,.78)',transform:`scale(${.9+.1*p})`,opacity:p*out,boxShadow:'0 18px 60px rgba(0,0,0,.38)'}}><div style={{width:62,height:62,borderRadius:16,background:O,color:D,font:'900 42px Arial',display:'grid',placeItems:'center'}}>!</div><div><div style={{font:'700 23px Arial',color:'#bdb8b1',letterSpacing:2}}>ALERTA FISCAL</div><div style={{font:'900 40px Arial',color:W}}>REGIME INADEQUADO</div></div></div>};
const BrandSeal:React.FC=()=>{const f=useCurrentFrame();const p=interpolate(f,[76,88],[0,1],{...clamp,easing:Easing.out(Easing.back(2))});return <div style={{position:'absolute',top:145,left:315,width:450,height:170,display:'flex',alignItems:'center',justifyContent:'center',gap:24,borderRadius:34,background:'rgba(8,9,11,.84)',border:'2px solid rgba(255,121,23,.7)',transform:`scale(${.82+.18*p})`,opacity:p,boxShadow:'0 0 55px rgba(255,121,23,.22)'}}><div style={{width:92,height:92,borderRadius:'50%',border:`5px solid ${O}`,display:'grid',placeItems:'center',font:'900 42px Arial',color:W}}>IC</div><div><div style={{font:'900 42px Arial',color:W}}>INTEGRA</div><div style={{font:'800 26px Arial',color:O,letterSpacing:3}}>CONTÁBIL</div></div></div>};
const Numbers:React.FC=()=>{const f=useCurrentFrame();const p=interpolate(f,[15,70],[0,1],{...clamp,easing:Easing.out(Easing.cubic)});return <div style={{position:'absolute',top:130,left:76,right:76,height:360,borderRadius:32,background:'rgba(7,8,10,.82)',border:'2px solid rgba(255,255,255,.14)',padding:34,boxSizing:'border-box'}}><div style={{font:'800 25px Arial',letterSpacing:3,color:'#c7c1b8'}}>DIAGNÓSTICO TRIBUTÁRIO</div><div style={{display:'flex',alignItems:'end',height:210,gap:28,marginTop:18}}>{[.36,.57,.78,1].map((v,i)=><div key={i} style={{flex:1,height:`${v*p*100}%`,minHeight:5,borderRadius:'14px 14px 0 0',background:i===3?O:'rgba(255,250,243,.55)',boxShadow:i===3?'0 0 28px rgba(255,121,23,.52)':'none'}}/>)}</div><div style={{position:'absolute',right:48,top:35,font:'900 42px Arial',color:O}}>ECONOMIA ↑</div></div>};

const Caption:React.FC<{t:Token;i:number}>=({t,i})=>{const f=useCurrentFrame();const d=t.e-t.s;const entry=interpolate(f,[0,Math.min(6,d/2)],[0,1],{...clamp,easing:Easing.out(Easing.back(1.65))});const out=interpolate(f,[Math.max(1,d-3),d],[1,0],clamp);const cta=t.emphasis==='cta';const rgb=t.emphasis==='rgb'||cta;const size=cta?94:t.text.length>16?78:t.text.length>12?92:112;const split=cta?t.text.split(' '):[t.text];return <div style={{position:'absolute',left:70,right:70,bottom:cta?230:185,minHeight:250,display:'flex',flexDirection:'column',justifyContent:'center',alignItems:'center',opacity:out,transform:`translateY(${(1-entry)*36}px) scale(${(.9+.1*entry)*(cta?1.06:1)})`,zIndex:20}}>{split.map((x,n)=><div key={n} style={{maxWidth:900,textAlign:'center',fontFamily:'Arial,Helvetica,sans-serif',fontSize:size,fontWeight:900,lineHeight:.91,letterSpacing:'-.045em',color:t.accent?O:W,textShadow:rgb?`${4+(cta?3:0)}px 0 rgba(255,30,55,.65),-${4+(cta?3:0)}px 0 rgba(20,180,255,.6),0 0 ${cta?42:25}px rgba(255,121,23,.8)`:'0 5px 28px rgba(0,0,0,.9)',overflowWrap:'normal'}}>{x}</div>)}</div>};
const CTA:React.FC=()=>{const f=useCurrentFrame();const p=interpolate(f,[13,23],[0,1],{...clamp,easing:Easing.out(Easing.back(2))});return <div style={{position:'absolute',left:150,right:150,bottom:88,height:116,borderRadius:58,background:O,display:'grid',placeItems:'center',transform:`scale(${.86+.14*p})`,boxShadow:'0 0 45px rgba(255,121,23,.55)',zIndex:25,font:'900 37px Arial',color:D}}>SOLICITAR AGORA <span style={{position:'absolute',right:36,fontSize:48}}>→</span></div>};
const Scene:React.FC<{from:number}>=({from})=>{if(from<120)return <><Broll src="broll-documents-ready.mp4" start={50}/><RiskHUD/></>;if(from<235)return <><Broll src="broll-team-ready.mp4" start={35}/><RegimeCard/><BrandSeal/></>;if(from<354)return <><Broll src="broll-calculator-ready.mp4" start={35}/><Numbers/></>;return <><AbsoluteFill style={{background:'radial-gradient(circle at 50% 35%,#46200b 0,#111216 42%,#07080a 78%)'}}/><div style={{position:'absolute',top:115,left:0,right:0,textAlign:'center',font:'800 26px Arial',letterSpacing:6,color:O}}>INTEGRA CONTÁBIL</div><CTA/></>};
const Sfx=({from,file,volume}:{from:number;file:string;volume:number})=><Sequence from={from}><Audio src={staticFile(file)} volume={volume}/></Sequence>;
const cuts=[120,235,354];
export const KineticVideo:React.FC<{bgm?:boolean}>=({bgm=true})=><AbsoluteFill style={{background:D,overflow:'hidden'}}>
 {bgm&&<Audio src={staticFile('shotcraft-house-vibez.mp3')} trimBefore={238} volume={(f)=>interpolate(f,[0,20,410,449],[0,.09,.09,0],clamp)}/>}<Audio src={staticFile('narracao-15s.wav')}/>
 <Sequence from={0} durationInFrames={120}><Scene from={0}/></Sequence><Sequence from={120} durationInFrames={115}><Scene from={120}/></Sequence><Sequence from={235} durationInFrames={119}><Scene from={235}/></Sequence><Sequence from={354} durationInFrames={96}><Scene from={354}/></Sequence>
 {T.map((t,i)=><Sequence key={t.s} from={t.s} durationInFrames={t.e-t.s}><Caption t={t} i={i}/></Sequence>)}
 {cuts.map(x=><React.Fragment key={x}><Sequence from={x-5} durationInFrames={10}><FlashCut/></Sequence><Sfx from={x-3} file="shotcraft-whoosh.mp3" volume={.1}/><Sfx from={x-1} file="shotcraft-light.mp3" volume={.055}/></React.Fragment>)}
 {T.map(t=><Sfx key={`p${t.s}`} from={t.s} file="shotcraft-pop.mp3" volume={t.emphasis?0.11:.075}/>)}<Sfx from={88} file="shotcraft-impact.mp3" volume={.14}/><Sfx from={395} file="shotcraft-impact.mp3" volume={.18}/>
 </AbsoluteFill>;
