import React from 'react';
import {AbsoluteFill,Audio,Easing,OffthreadVideo,Sequence,interpolate,staticFile,useCurrentFrame} from 'remotion';

const NAVY='#071d2d',NAVY2='#0d3045',GREEN='#087f68',CREAM='#f5f1e8',RED='#bd2437';
type Cue={s:number;e:number;t:string};const f=(s:number)=>Math.round(s*30);
const CUES:Cue[]=[
 [12.78,15.55,'Eles fazem parte do novo\nmodelo de tributação'],[15.55,18.38,'sobre o consumo, criado pela\nREFORMA TRIBUTÁRIA.'],[18.38,20.88,'E por que isso importa\npara você, empresário?'],[20.88,24.62,'Porque a mudança não envolve apenas\ntrocar o nome dos impostos.'],[30.94,34.45,'Por isso você, empresário, precisa\ncomeçar a entender a mudança'],[34.45,37.9,'antes que ela vire um\nPROBLEMA OPERACIONAL.'],[37.9,40.65,'Quer que eu explique\na reforma tributária'],[40.65,43.14,'de forma mais simples, sem\ncontabilidade complicada?']
].map(([s,e,t])=>({s:f(s as number),e:f(e as number),t:t as string}));

const City=()=> <div style={{position:'absolute',top:300,right:40,background:RED,color:'#fff',padding:'13px 20px',font:'900 31px Arial',letterSpacing:.5,boxShadow:'0 5px 14px rgba(0,0,0,.25)'}}>PARAUAPEBAS</div>;
const Caption=({cue}:{cue:Cue})=>{const frame=useCurrentFrame(),local=frame-cue.s,out=interpolate(frame,[cue.e-7,cue.e],[0,1],{extrapolateLeft:'clamp',extrapolateRight:'clamp',easing:Easing.in(Easing.cubic)});return <div style={{font:'800 58px/1.1 Arial',color:'#fff',whiteSpace:'pre-line',textAlign:'center',textShadow:'0 4px 9px rgba(0,0,0,.78)',opacity:1-out,filter:`blur(${out*9}px)`,transform:`translateY(${-out*12}px)`}}>{cue.t.split(/(\s+)/).map((w,i)=>{if(/^\s+$/.test(w))return w;const p=interpolate(local,[Math.min(i*.7,7),Math.min(i*.7,7)+10],[0,1],{extrapolateLeft:'clamp',extrapolateRight:'clamp',easing:Easing.out(Easing.cubic)});const hi=/REFORMA|TRIBUTÁRIA|PROBLEMA|OPERACIONAL/.test(w);return <span key={i} style={{display:'inline-block',color:hi?'#45d3b0':'#fff',opacity:p,filter:`blur(${(1-p)*10}px)`,transform:`translateY(${(1-p)*25}px)`}}>{w}</span>})}</div>};

const charY=(frame:number,i:number)=>{const t=6+i*2;if(frame<t+14)return interpolate(frame,[t,t+14],[115,-10],{extrapolateLeft:'clamp',extrapolateRight:'clamp',easing:Easing.out(Easing.cubic)});return interpolate(frame,[t+14,t+20],[-10,0],{extrapolateLeft:'clamp',extrapolateRight:'clamp',easing:Easing.out(Easing.quad)})};
const SplitWord=({word,frame,color}:{word:string;frame:number;color:string})=><div style={{display:'flex',justifyContent:'center'}}>{word.split('').map((c,i)=><div key={i} style={{overflow:'hidden',height:190,display:'flex',alignItems:'flex-end'}}><span style={{font:'900 175px/1 Arial',color,display:'inline-block',transform:`translateY(${charY(frame,i)}%)`}}>{c}</span></div>)}</div>;
const Hook=()=>{const frame=useCurrentFrame(),out=interpolate(frame,[145,166],[0,1],{extrapolateLeft:'clamp',extrapolateRight:'clamp',easing:Easing.in(Easing.cubic)});return <div style={{position:'absolute',inset:0,opacity:1-out,fontFamily:'Arial'}}><div style={{position:'absolute',top:490,left:70}}><SplitWord word="IBS" frame={frame} color={GREEN}/></div><div style={{position:'absolute',top:490,right:45,transform:'scale(.72)',transformOrigin:'top right'}}><SplitWord word="CBS" frame={frame-8} color={NAVY2}/></div><div style={{position:'absolute',left:60,right:60,top:1450,textAlign:'center',font:'900 62px/1.05 Arial',color:'#fff',textShadow:'0 4px 10px rgba(0,0,0,.75)'}}>VOCÊ SABE O QUE<br/><span style={{color:'#45d3b0'}}>ELES SIGNIFICAM?</span></div></div>};

const Compare=()=>{const frame=useCurrentFrame(),local=frame-167;const line=interpolate(local,[5,28],[0,100],{extrapolateLeft:'clamp',extrapolateRight:'clamp',easing:Easing.out(Easing.cubic)});const item=(start:number)=>interpolate(local,[start,start+22],[0,1],{extrapolateLeft:'clamp',extrapolateRight:'clamp',easing:Easing.out(Easing.back(1.1))});return <AbsoluteFill style={{background:`linear-gradient(145deg,${NAVY},${NAVY2})`,fontFamily:'Arial',color:'#fff',alignItems:'center'}}><div style={{position:'absolute',top:335,font:'800 35px Arial',letterSpacing:7,color:'#8bb4c5'}}>VAMOS SIMPLIFICAR</div><div style={{position:'absolute',top:600,display:'flex',width:1160,justifyContent:'space-between',alignItems:'flex-start'}}>{[{a:'CBS',b:'TRIBUTO FEDERAL',p:item(20)},{a:'IBS',b:'ESTADUAL + MUNICIPAL',p:item(65)}].map(x=><div key={x.a} style={{width:510,textAlign:'center',opacity:x.p,transform:`scale(${.78+x.p*.22}) translateY(${(1-x.p)*18}px)`}}><div style={{fontSize:210,fontWeight:900,lineHeight:.92,color:x.a==='CBS'?'#fff':'#45d3b0'}}>{x.a}</div><div style={{marginTop:34,fontSize:45,fontWeight:800,lineHeight:1.12}}>{x.b}</div></div>)}</div><div style={{position:'absolute',top:1125,width:`${line}%`,maxWidth:1140,height:5,background:GREEN}}/><div style={{position:'absolute',top:1260,left:150,right:150,textAlign:'center',font:'700 48px/1.25 Arial',color:'#cfe2e8',opacity:item(105)}}>NOVO MODELO DE TRIBUTAÇÃO<br/>SOBRE O CONSUMO</div></AbsoluteFill>};

const Impacts=()=>{const frame=useCurrentFrame(),local=frame-739,items=['PROCESSOS FISCAIS','DOCUMENTOS','CRÉDITOS TRIBUTÁRIOS','FORMAÇÃO DO PREÇO'];return <AbsoluteFill style={{background:`linear-gradient(145deg,${CREAM},#dce9e5)`,fontFamily:'Arial',color:NAVY,justifyContent:'center',alignItems:'center'}}><div style={{position:'absolute',top:310,font:'900 52px Arial',letterSpacing:3,color:GREEN}}>O QUE PODE MUDAR?</div><div style={{display:'flex',flexDirection:'column',gap:30,transform:`translateY(${interpolate(local,[0,189],[16,-16])}px)`}}>{items.map((s,i)=>{const p=interpolate(local,[18+i*26,44+i*26],[0,1],{extrapolateLeft:'clamp',extrapolateRight:'clamp',easing:Easing.out(Easing.back(1.1))});return <div key={s} style={{width:1020,padding:'25px 35px',background:'rgba(255,255,255,.66)',borderLeft:`10px solid ${GREEN}`,fontSize:52,fontWeight:900,opacity:Math.min(1,p*2.2),transform:`scale(${.78+p*.22}) translateY(${(1-p)*14}px)`,boxShadow:'0 10px 24px rgba(7,29,45,.1)'}}>{s}</div>})}</div></AbsoluteFill>};

const CTA=()=>{const frame=useCurrentFrame(),local=frame-1294,p=interpolate(local,[0,24],[0,1],{extrapolateLeft:'clamp',extrapolateRight:'clamp',easing:Easing.out(Easing.cubic)}),p2=interpolate(local,[20,48],[0,1],{extrapolateLeft:'clamp',extrapolateRight:'clamp',easing:Easing.out(Easing.cubic)});return <AbsoluteFill style={{background:`linear-gradient(155deg,${NAVY},#0a473f)`,fontFamily:'Arial',color:'#fff',justifyContent:'center',alignItems:'center',textAlign:'center'}}><div style={{fontSize:110,fontWeight:900,lineHeight:.95,opacity:p,filter:`blur(${(1-p)*10}px)`,transform:`translateY(${(1-p)*40}px)`}}>SIGA E<br/><span style={{color:'#45d3b0'}}>ACOMPANHE</span></div><div style={{marginTop:55,fontSize:49,fontWeight:800,letterSpacing:3,opacity:p2,filter:`blur(${(1-p2)*8}px)`,transform:`translateY(${(1-p2)*26}px)`}}>OS PRÓXIMOS VÍDEOS</div></AbsoluteFill>};

export const Integra01:React.FC=()=>{const frame=useCurrentFrame(),hook=frame<167,compare=frame>=167&&frame<383,impacts=frame>=739&&frame<928,cta=frame>=1294&&frame<1395,special=hook||compare||impacts||cta;return <AbsoluteFill style={{background:'#000'}}><OffthreadVideo src={staticFile('integra01.mp4')}/>{!special&&<><City/><div style={{position:'absolute',left:75,right:75,top:1480,height:210,display:'flex',alignItems:'center',justifyContent:'center'}}>{CUES.filter(c=>frame>=c.s&&frame<c.e).map(c=><Caption key={c.s} cue={c}/>)}</div></>}{hook&&<><City/><Hook/></>}{compare&&<Compare/>}{impacts&&<Impacts/>}{cta&&<CTA/>}
<Sequence from={6} durationInFrames={25}><Audio src={staticFile('sfx/transition-soft.mp3')} volume={.3}/></Sequence><Sequence from={167} durationInFrames={50}><Audio src={staticFile('sfx/transition-tech.mp3')} volume={.27}/></Sequence>{[187,232].map(x=><Sequence key={x} from={x} durationInFrames={20}><Audio src={staticFile('sfx/pop-electric.mp3')} volume={.2}/></Sequence>)}<Sequence from={739} durationInFrames={30}><Audio src={staticFile('sfx/transition-soft.mp3')} volume={.3}/></Sequence>{[757,783,809,835].map(x=><Sequence key={x} from={x} durationInFrames={18}><Audio src={staticFile('sfx/hitech-touch-magnet.mp3')} volume={.17}/></Sequence>)}<Sequence from={1294} durationInFrames={35}><Audio src={staticFile('sfx/impact-deep-whoosh.mp3')} volume={.23}/></Sequence>
</AbsoluteFill>};
